// Expo's ambient types (CSS modules, process.env.EXPO_PUBLIC_*). expo-env.d.ts does the same but is
// generated by `expo start` and git-ignored, so typecheck would fail on a fresh clone without this.
/// <reference types="expo/types" />
