/// <reference types="node" />
/**
 * Writes supabase/tests/database/08_rank_distribution.test.sql: the 50 fake lifters from
 * fakeUsers.ts, run through the Postgres rank engine and checked against the TypeScript mirror.
 * The test prints the tier distribution (pgTAP diag) and fails if the two engines disagree.
 *
 * Run with `pnpm ranks:fake` after changing the engine, the standards or the fake users.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { exercises } from './exercises.ts';
import { distributionTable, makeFakeUsers, rankFakeUsers } from './fakeUsers.ts';
import { rankConfig } from './standards.ts';

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'tests',
  'database',
  '08_rank_distribution.test.sql',
);

const text = (value: string) => `'${value.replace(/'/g, "''")}'`;

function main() {
  const now = new Date();
  const results = rankFakeUsers(makeFakeUsers(), rankConfig, exercises, now);
  const rows = results.map(({ user, scores }) => {
    const data = {
      bw: user.bodyweights,
      w: user.workouts.map((w) => [w.daysAgo, w.sets]),
    };
    const expected = Object.fromEntries(
      Object.entries(scores).map(([k, v]) => [k, v === null ? null : Math.round(v * 100) / 100]),
    );
    return `  (${text(user.id)}, ${text(user.level)}, ${text(user.sex)}, ${user.age}, ${text(JSON.stringify(data))}, ${text(JSON.stringify(expected))})`;
  });
  const setCount = results.reduce(
    (sum, r) => sum + r.user.workouts.reduce((n, w) => n + w.sets.length, 0),
    0,
  );

  const sql = `-- GENERATED by supabase/seed/buildFakeUsers.ts (pnpm ranks:fake). Do not edit by hand.
-- 50 fake lifters with realistic histories (supabase/seed/fakeUsers.ts): ${setCount} sets.
-- Runs them through the Postgres rank engine, prints the overall tier distribution by experience,
-- and checks every lift, overall and discipline score matches the TypeScript mirror (±0.5).
-- Dates are relative to now(), so the result doesn't depend on when it runs.
--
-- Distribution when generated (TypeScript mirror):
${distributionTable(results)
  .map((l) => `--   ${l}`)
  .join('\n')}
begin;
set local role postgres;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;

select plan(6);

create temp table fake (
  id uuid primary key, level text, sex text, age integer, data jsonb, expected jsonb
);
insert into fake values
${rows.join(',\n')};

insert into auth.users (id, email) select id, id || '@fake.test' from fake;
update public.profiles p set
  sex_for_standards = f.sex::public.sex_for_standards,
  birth_year = (extract(year from now() at time zone 'utc')::integer - f.age)::smallint
from fake f where p.id = f.id;

insert into public.bodyweight_logs (user_id, weight_kg, logged_at)
select f.id, (b ->> 1)::numeric, now() - (b ->> 0)::integer * interval '1 day'
from fake f, jsonb_array_elements(f.data -> 'bw') b;

create temp table fake_workouts as
select f.id as user_id, md5(f.id::text || ':' || wi)::uuid as workout_id,
  (w ->> 0)::integer as days_ago, w -> 1 as sets
from fake f, jsonb_array_elements(f.data -> 'w') with ordinality as x(w, wi);

insert into public.workouts (id, user_id, name, started_at, ended_at, status, client_updated_at)
select workout_id, user_id, 'Fake session', now() - days_ago * interval '1 day',
  now() - days_ago * interval '1 day' + interval '1 hour', 'completed', now()
from fake_workouts;

insert into public.workout_exercises (id, workout_id, exercise_id, sort_order)
select md5(fw.workout_id::text || ':' || si)::uuid, fw.workout_id, x.id, si - 1
from fake_workouts fw, jsonb_array_elements(fw.sets) with ordinality as s(st, si)
join public.exercises x on x.slug = st ->> 0 and x.created_by is null;

insert into public.workout_sets (id, workout_exercise_id, sort_order, set_type, weight_mode,
  reps, weight_kg, duration_sec, completed, completed_at)
select md5(fw.workout_id::text || ':' || si || ':set')::uuid,
  md5(fw.workout_id::text || ':' || si)::uuid, 0, 'working',
  case when x.log_type = 'weight_reps' then 'absolute' else 'bodyweight' end::public.weight_mode,
  (st ->> 2)::smallint, (st ->> 1)::numeric, (st ->> 3)::integer, true,
  now() - fw.days_ago * interval '1 day' + (si - 1) * interval '1 minute'
from fake_workouts fw, jsonb_array_elements(fw.sets) with ordinality as s(st, si)
join public.exercises x on x.slug = st ->> 0 and x.created_by is null;

select is((select count(*) from public.workout_sets s
  join public.workout_exercises we on we.id = s.workout_exercise_id
  join fake_workouts fw on fw.workout_id = we.workout_id), ${setCount}::bigint,
  'all ${setCount} fake sets are in');

select is(
  (select count(*) from fake f where public.rank_recompute_user(f.id) is null), 50::bigint,
  'the engine recomputes all 50 lifters'
);

-- Scores the TypeScript mirror expects, against what Postgres stored.
create temp table compare as
select f.id, f.level, e.key, nullif(e.value, 'null'::jsonb)::numeric as expected, c.score as actual
from fake f
cross join lateral jsonb_each(f.expected) e
left join public.ranks_current c
  on c.user_id = f.id and c.scope::text || ':' || c.key = e.key;

select is(
  (select count(*) from compare
   where (expected is null) <> (actual is null) or abs(expected - actual) > 0.5),
  0::bigint,
  'Postgres matches the TypeScript mirror on every lift, overall and discipline score'
);

select is(
  (select count(*) from public.ranks_current c join fake f on f.id = c.user_id
   where c.scope in ('lift', 'overall', 'weightlifting', 'calisthenics')),
  (select count(*) from compare),
  'and ranks nothing the mirror doesn''t'
);

select diag(line) from (
  select format('%-14s %s', level, string_agg(format('%s %s', coalesce(tier::text, 'unplaced'), n), ', ' order by o)) as line
  from (
    select f.level, c.tier, count(*) as n,
      coalesce(array_position(enum_range(null::public.rank_tier), c.tier), 99) as o
    from fake f
    join public.ranks_current c on c.user_id = f.id and c.scope = 'overall'
    group by f.level, c.tier
  ) t
  group by level
  order by min(case level when 'beginner' then 1 when 'novice' then 2 when 'intermediate' then 3
    when 'advanced' then 4 else 5 end)
) d;

select ok(
  (select count(*) filter (where c.tier in ('iron', 'bronze', 'silver')) >= 0.8 * count(*)
   from fake f join public.ranks_current c on c.user_id = f.id and c.scope = 'overall'
   where f.level = 'beginner'),
  'most beginners are Iron–Silver'
);
select ok(
  (select count(*) filter (where c.tier in ('gold', 'platinum')) >= 0.6 * count(*)
   from fake f join public.ranks_current c on c.user_id = f.id and c.scope = 'overall'
   where f.level = 'intermediate'),
  'most 1–2 year lifters are Gold–Platinum (Master and Champion stay rare: see the diag above)'
);

select * from finish();
rollback;
`;
  writeFileSync(OUT, sql);
  console.log(
    `Wrote supabase/tests/database/08_rank_distribution.test.sql: 50 lifters, ${setCount} sets.`,
  );
}

main();
