/// <reference types="node" />
/**
 * Validates the strength standards and writes them as a migration:
 *   supabase/migrations/<timestamp>_strength_standards_v<STANDARDS_VERSION>.sql
 *
 * Run with `pnpm standards:build`. Re-running for the same version rewrites that version's file;
 * bump STANDARDS_VERSION for a new one. Applying it makes the version active, which queues every
 * lifter for a recompute (pg_cron picks them up within a minute).
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { RankConfig } from '../../src/lib/game/engine/types.ts';
import { exercises } from './exercises.ts';
import { rankConfig, STANDARDS_VERSION } from './standards.ts';
import { validateStandards } from './standards/validate.ts';

const MIGRATIONS_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'migrations');

const text = (value: string) => `'${value.replace(/'/g, "''")}'`;
const num = (value: number | null) => (value === null ? 'null' : String(value));
const numArray = (values: readonly number[]) => `'{${values.join(',')}}'::numeric[]`;

function buildSql(config: RankConfig): string {
  const v = config.version;
  const s = config.settings;
  const lifts = config.lifts.map(
    (l) =>
      `  (${text(l.rankKey)}, ${text(l.name)}, ${text(l.discipline)}::public.rank_discipline, ` +
      `${num(l.maxRatio)}, ${num(l.maxReps)}, ${num(l.maxHoldSec)})`,
  );
  const variants = config.variants.map((x) => `  (${text(x.slug)}, ${text(x.rankKey)})`);
  const standards = config.standards.map(
    (r) =>
      `  (${v}, ${text(r.rankKey)}, ${text(r.variant)}, ${text(r.sex)}::public.sex_for_standards, ` +
      `${r.bwMin}, ${r.bwMax}, ${text(r.metric)}::public.standard_metric, ` +
      `${numArray(r.anchorScores)}, ${numArray(r.anchorValues)}, ${r.maxScore})`,
  );
  const thresholds = config.thresholds.map(
    (t) => `  (${v}, ${text(t.tier)}::public.rank_tier, ${num(t.division)}, ${t.minScore})`,
  );
  const regions = Object.entries(config.regionWeights).map(
    ([region, weight]) => `  (${text(region)}::public.muscle_region, ${weight})`,
  );
  const ages = config.ageBrackets.map((b) => `  (${b.minAge}, ${num(b.maxAge)}, ${b.factor})`);

  return `-- Strength standards v${v}: ${config.lifts.length} lifts, ${config.standards.length} standard rows.
-- GENERATED by supabase/seed/buildStandards.ts from supabase/seed/standards.ts. Do not edit by hand.
-- Idempotent. Making the version active queues every lifter for a recompute (rank_settings trigger).

insert into public.rank_lifts (rank_key, name, discipline, max_ratio, max_reps, max_hold_sec)
values
${lifts.join(',\n')}
on conflict (rank_key) do update set
  name = excluded.name,
  discipline = excluded.discipline,
  max_ratio = excluded.max_ratio,
  max_reps = excluded.max_reps,
  max_hold_sec = excluded.max_hold_sec;

delete from public.rank_variants;
insert into public.rank_variants (slug, rank_key)
values
${variants.join(',\n')};

delete from public.strength_standards where version = ${v};
insert into public.strength_standards (version, rank_key, variant, sex, bw_min, bw_max, metric,
  anchor_scores, anchor_values, max_score)
values
${standards.join(',\n')};

delete from public.rank_thresholds where version = ${v};
insert into public.rank_thresholds (version, tier, division, min_score)
values
${thresholds.join(',\n')};

delete from public.rank_region_weights;
insert into public.rank_region_weights (region, weight)
values
${regions.join(',\n')};

delete from public.strength_age_brackets;
insert into public.strength_age_brackets (min_age, max_age, factor)
values
${ages.join(',\n')};

update public.rank_settings set
  active_standards_version = ${v},
  window_days = ${s.windowDays},
  inactive_days = ${s.inactiveDays},
  placement_lifts = ${s.placementLifts},
  placement_regions = ${s.placementRegions},
  discipline_min_lifts = ${s.disciplineMinLifts},
  bw_window_days = ${s.bwWindowDays},
  max_score = ${s.maxScore},
  updated_at = now();
`;
}

function timestamp(): string {
  return new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14);
}

function main() {
  const problems = validateStandards(rankConfig, exercises);
  if (problems.length > 0) {
    console.error(`Strength standards have ${problems.length} problem(s):`);
    for (const problem of problems) console.error(`  • ${problem}`);
    process.exit(1);
  }
  const suffix = `_strength_standards_v${STANDARDS_VERSION}.sql`;
  const existing = readdirSync(MIGRATIONS_DIR).find((file) => file.endsWith(suffix));
  const file = existing ?? `${timestamp()}${suffix}`;
  writeFileSync(join(MIGRATIONS_DIR, file), buildSql(rankConfig));
  console.log(
    `${existing ? 'Rewrote' : 'Wrote'} supabase/migrations/${file}: ` +
      `${rankConfig.lifts.length} lifts, ${rankConfig.standards.length} standard rows, v${STANDARDS_VERSION}.`,
  );
}

main();
