/// <reference types="node" />
/**
 * Validates the official exercise library and writes it as a migration:
 *   supabase/migrations/<timestamp>_exercise_library_v<LIBRARY_VERSION>.sql
 *
 * Run with `pnpm exercises:build` (Node strips the types natively). Re-running for the same
 * version rewrites that version's file in place; bump LIBRARY_VERSION for a new migration.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { ExerciseSeed } from './define.ts';
import { exercises, LIBRARY_VERSION } from './exercises.ts';
import { validateLibrary } from './validate.ts';

const MIGRATIONS_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'migrations');

const text = (value: string) => `'${value.replace(/'/g, "''")}'`;
const textArray = (values: string[]) =>
  values.length === 0 ? `'{}'::text[]` : `array[${values.map(text).join(', ')}]`;
const nullable = (value: string | null) => (value === null ? 'null' : text(value));

function exerciseRow(e: ExerciseSeed): string {
  return `  (${[
    text(e.slug),
    text(e.name),
    textArray(e.aliases),
    `${text(e.category)}::public.exercise_category`,
    `${text(e.equipment)}::public.equipment`,
    `${text(e.mechanic)}::public.exercise_mechanic`,
    `${text(e.logType)}::public.exercise_log_type`,
    String(e.unilateral),
    textArray(e.instructions),
    textArray(e.tips),
    textArray(e.mistakes),
    e.met.toFixed(1),
    String(e.rankKey !== null),
    nullable(e.rankKey),
  ].join(', ')})`;
}

function muscleRows(list: ExerciseSeed[]): string[] {
  return list.flatMap((e) =>
    e.muscles.map((m) => `  (${text(e.slug)}, ${text(m.muscle)}, ${text(m.role)}, ${m.weight})`),
  );
}

function buildSql(list: ExerciseSeed[], version: number): string {
  const muscleCount = list.reduce((sum, e) => sum + e.muscles.length, 0);
  return `-- Official exercise library v${version}: ${list.length} exercises, ${muscleCount} muscle links.
-- GENERATED by supabase/seed/build.ts from supabase/seed/exercises.ts. Do not edit by hand.
-- Idempotent: upserts on the official slug, so exercise ids stay stable across versions.

-- Rank keys may move between exercises in a new version; clear them first so the unique index holds.
update public.exercises set rank_key = null, is_rankable = false
where created_by is null and rank_key is not null;

insert into public.exercises (
  slug, name, aliases, category, equipment, mechanic, log_type, unilateral,
  instructions, tips, common_mistakes, met_value, is_rankable, rank_key, created_by, is_public
)
select v.*, null::uuid, true
from (values
${list.map(exerciseRow).join(',\n')}
) as v (
  slug, name, aliases, category, equipment, mechanic, log_type, unilateral,
  instructions, tips, common_mistakes, met_value, is_rankable, rank_key
)
on conflict (slug) where created_by is null do update set
  name = excluded.name,
  aliases = excluded.aliases,
  category = excluded.category,
  equipment = excluded.equipment,
  mechanic = excluded.mechanic,
  log_type = excluded.log_type,
  unilateral = excluded.unilateral,
  instructions = excluded.instructions,
  tips = excluded.tips,
  common_mistakes = excluded.common_mistakes,
  met_value = excluded.met_value,
  is_rankable = excluded.is_rankable,
  rank_key = excluded.rank_key;

delete from public.exercise_muscles em
using public.exercises e
where em.exercise_id = e.id and e.created_by is null;

insert into public.exercise_muscles (exercise_id, muscle, role, weight)
select e.id, v.muscle::public.muscle, v.role::public.muscle_role, v.weight
from (values
${muscleRows(list).join(',\n')}
) as v (slug, muscle, role, weight)
join public.exercises e on e.slug = v.slug and e.created_by is null;

do $$
begin
  if (select count(*) from public.exercise_muscles em
      join public.exercises e on e.id = em.exercise_id
      where e.created_by is null) <> ${muscleCount} then
    raise exception 'Exercise library v${version}: muscle links did not all insert.';
  end if;
end;
$$;

update public.exercise_library_meta set version = ${version}, updated_at = now();
`;
}

function timestamp(): string {
  return new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14);
}

function main() {
  const problems = validateLibrary(exercises);
  if (problems.length > 0) {
    console.error(`Exercise library has ${problems.length} problem(s):`);
    for (const problem of problems) console.error(`  • ${problem}`);
    process.exit(1);
  }

  const suffix = `_exercise_library_v${LIBRARY_VERSION}.sql`;
  const existing = readdirSync(MIGRATIONS_DIR).find((file) => file.endsWith(suffix));
  const file = existing ?? `${timestamp()}${suffix}`;
  writeFileSync(join(MIGRATIONS_DIR, file), buildSql(exercises, LIBRARY_VERSION));

  const rankable = exercises.filter((e) => e.rankKey !== null).length;
  console.log(
    `${existing ? 'Rewrote' : 'Wrote'} supabase/migrations/${file}: ` +
      `${exercises.length} exercises (${rankable} rankable), library v${LIBRARY_VERSION}.`,
  );
}

main();
