import { defineExercises } from '../define.ts';

export const arms = defineExercises([
  // ─── Biceps ───
  {
    name: 'Barbell curl',
    aliases: ['bb curl', 'standing barbell curl', 'bicep curl barbell', 'straight bar curl'],
    equipment: 'barbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    rankKey: 'barbellCurl',
    primary: ['biceps'],
    secondary: ['forearms'],
    instructions: [
      'Stand holding a barbell with an underhand grip, hands shoulder width apart.',
      'Keeping your elbows at your sides, curl the bar up to your shoulders.',
      'Lower it slowly until your arms are straight.',
    ],
    tips: ['Keep your upper arms still; only your forearms move.'],
    mistakes: ['Swinging the weight up with your hips.', 'Letting your elbows drift forward.'],
  },
  {
    name: 'EZ-bar curl',
    aliases: ['ez curl', 'cambered bar curl'],
    equipment: 'barbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['biceps'],
    secondary: ['forearms'],
    instructions: [
      'Hold an EZ bar on the angled grips, palms angled up.',
      'Curl the bar to your shoulders with your elbows at your sides.',
      'Lower slowly.',
    ],
    tips: ['Easier on the wrists than a straight bar.'],
  },
  {
    name: 'Dumbbell curl',
    aliases: [
      'bicep curl',
      'biceps curl',
      'db curl',
      'alternating dumbbell curl',
      'standing dumbbell curl',
    ],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    rankKey: 'dumbbellCurl',
    primary: ['biceps'],
    light: ['forearms'],
    instructions: [
      'Stand holding dumbbells at your sides, palms facing forward.',
      'Curl the dumbbells up to your shoulders, keeping your elbows still.',
      'Lower slowly until your arms are straight.',
    ],
    tips: ['Log the weight of one dumbbell.'],
    mistakes: ['Swinging the body.', 'Not straightening the arm at the bottom.'],
  },
  {
    name: 'Hammer curl',
    aliases: ['db hammer curl', 'neutral grip curl'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['biceps', 'forearms'],
    instructions: [
      'Stand holding dumbbells at your sides, palms facing your thighs.',
      'Curl them up with your thumbs pointing up.',
      'Lower slowly.',
    ],
    tips: ['Builds the brachialis and brachioradialis for thicker arms.'],
  },
  {
    name: 'Incline dumbbell curl',
    aliases: ['incline curl'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['biceps'],
    instructions: [
      'Sit back on a 45–60° incline bench with dumbbells hanging straight down.',
      'Curl the dumbbells up without moving your upper arms.',
      'Lower all the way to a full stretch.',
    ],
    tips: ['The stretched start makes lighter weights feel heavy; that’s the point.'],
  },
  {
    name: 'EZ-bar preacher curl',
    aliases: ['preacher curl', 'scott curl'],
    equipment: 'barbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['biceps'],
    instructions: [
      'Sit at a preacher bench with your upper arms flat on the pad.',
      'Hold an EZ bar with an underhand grip and curl it up.',
      'Lower slowly until your arms are almost straight.',
    ],
    mistakes: ['Dropping fast into the bottom, which stresses the elbow.'],
  },
  {
    name: 'Machine preacher curl',
    aliases: ['bicep curl machine', 'machine curl'],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['biceps'],
    instructions: [
      'Adjust the seat so your upper arms lie flat on the pad.',
      'Curl the handles towards your shoulders.',
      'Lower under control.',
    ],
  },
  {
    name: 'Concentration curl',
    aliases: ['seated concentration curl'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['biceps'],
    instructions: [
      'Sit on a bench and rest the back of your upper arm against your inner thigh.',
      'Curl the dumbbell up towards your shoulder.',
      'Lower slowly and switch arms after the set.',
    ],
  },
  {
    name: 'Cable curl',
    aliases: ['cable bicep curl', 'straight bar cable curl'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['biceps'],
    light: ['forearms'],
    instructions: [
      'Attach a straight bar to a low pulley and hold it underhand.',
      'Curl the bar to your shoulders with your elbows at your sides.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Cable rope hammer curl',
    aliases: ['rope hammer curl', 'rope curl'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['biceps', 'forearms'],
    instructions: [
      'Attach a rope to a low pulley and hold the ends with palms facing each other.',
      'Curl the rope up towards your shoulders.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Bayesian cable curl',
    aliases: ['bayesian curl', 'behind the body cable curl'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['biceps'],
    instructions: [
      'Set a pulley low, face away from it and hold the handle with your arm behind your body.',
      'Step forward so the cable pulls your arm back into a stretch.',
      'Curl the handle forward and up, then lower slowly. Switch arms after the set.',
    ],
  },
  {
    name: 'Spider curl',
    aliases: ['prone incline curl'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['biceps'],
    instructions: [
      'Lie chest-down on an incline bench with dumbbells hanging straight down.',
      'Curl them up, keeping your upper arms vertical.',
      'Squeeze at the top and lower slowly.',
    ],
  },
  {
    name: 'Reverse barbell curl',
    aliases: ['reverse curl', 'overhand curl'],
    equipment: 'barbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['forearms'],
    secondary: ['biceps'],
    instructions: [
      'Hold a barbell or EZ bar with an overhand grip.',
      'Curl it up, keeping your wrists straight.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Resistance band curl',
    aliases: ['band curl', 'band bicep curl'],
    equipment: 'band',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    primary: ['biceps'],
    instructions: [
      'Stand on the middle of a band and hold an end in each hand.',
      'Curl your hands up to your shoulders.',
      'Lower slowly against the band.',
    ],
  },
  // ─── Triceps ───
  {
    name: 'Cable triceps pushdown',
    aliases: [
      'tricep pushdown',
      'pushdown',
      'triceps pushdown',
      'bar pushdown',
      'tricep pressdown',
    ],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['triceps'],
    instructions: [
      'Attach a straight or angled bar to a high pulley and grip it overhand.',
      'Keep your elbows pinned to your sides and push the bar down until your arms are straight.',
      'Let it rise back to chest height under control.',
    ],
    mistakes: ['Elbows drifting forward.', 'Leaning over the bar and using bodyweight.'],
  },
  {
    name: 'Cable rope pushdown',
    aliases: ['rope pushdown', 'rope tricep pushdown', 'rope pressdown'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['triceps'],
    instructions: [
      'Attach a rope to a high pulley and hold the ends with palms facing each other.',
      'Push down and spread the rope ends apart at the bottom.',
      'Return slowly.',
    ],
  },
  {
    name: 'Reverse-grip pushdown',
    aliases: ['underhand pushdown', 'reverse grip tricep pushdown'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['triceps'],
    instructions: [
      'Grip a straight bar on a high pulley with your palms facing up.',
      'Push down until your arms are straight, elbows at your sides.',
      'Return slowly.',
    ],
  },
  {
    name: 'Overhead cable triceps extension',
    aliases: ['overhead rope extension', 'cable overhead extension', 'french press cable'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['triceps'],
    instructions: [
      'Face away from a pulley with a rope held behind your head, elbows pointing forward.',
      'Extend your arms forward and up until they’re straight.',
      'Bend back slowly into a stretch.',
    ],
    tips: ['The overhead stretch works the long head of the triceps hardest.'],
  },
  {
    name: 'Dumbbell overhead triceps extension',
    aliases: [
      'overhead extension',
      'french press',
      'seated tricep extension',
      'db overhead extension',
    ],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['triceps'],
    instructions: [
      'Sit or stand holding one dumbbell overhead with both hands.',
      'Lower it behind your head by bending your elbows.',
      'Extend back up until your arms are straight.',
    ],
    mistakes: ['Elbows flaring wide.', 'Arching the lower back.'],
  },
  {
    name: 'EZ-bar skull crusher',
    aliases: ['skull crusher', 'skullcrusher', 'lying triceps extension', 'nose breaker'],
    equipment: 'barbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['triceps'],
    instructions: [
      'Lie on a flat bench holding an EZ bar above your chest with straight arms.',
      'Bend your elbows to lower the bar towards your forehead or just behind your head.',
      'Extend your arms back to the start.',
    ],
    tips: ['Lowering behind the head keeps tension on the triceps and is kinder to the elbows.'],
    mistakes: ['Letting the elbows flare out.'],
  },
  {
    name: 'Dumbbell triceps kickback',
    aliases: ['kickback', 'tricep kickback'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['triceps'],
    instructions: [
      'Hinge forward with one hand on a bench and your upper arm held parallel to the floor.',
      'Straighten your arm behind you.',
      'Lower slowly and switch arms after the set.',
    ],
  },
  {
    name: 'Bench dip',
    aliases: ['chair dip', 'tricep dip bench'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    primary: ['triceps'],
    light: ['mid_lower_chest', 'front_delts'],
    instructions: [
      'Sit on the edge of a bench, hands beside your hips, and walk your feet out.',
      'Bend your elbows to lower your hips towards the floor.',
      'Press back up until your arms are straight.',
    ],
    tips: ['Bend your knees to make it easier, or raise your feet to make it harder.'],
    mistakes: ['Dropping so low your shoulders roll forward.'],
  },
  {
    name: 'Seated dip machine',
    aliases: ['dip machine', 'tricep dip machine'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['triceps'],
    secondary: ['mid_lower_chest'],
    instructions: [
      'Sit with the handles beside your hips.',
      'Press down until your arms are straight.',
      'Let the handles rise slowly.',
    ],
  },
  // ─── Forearms ───
  {
    name: 'Barbell wrist curl',
    aliases: ['wrist curl', 'seated wrist curl'],
    equipment: 'barbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['forearms'],
    instructions: [
      'Sit with your forearms on your thighs or a bench, palms up, holding a barbell.',
      'Let the bar roll down to your fingertips.',
      'Curl your wrists up as high as you can.',
    ],
  },
  {
    name: 'Dumbbell reverse wrist curl',
    aliases: ['reverse wrist curl', 'wrist extension'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['forearms'],
    instructions: [
      'Rest your forearms on a bench, palms down, holding light dumbbells.',
      'Lift the backs of your hands up as far as you can.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Wrist roller',
    aliases: ['forearm roller'],
    equipment: 'other',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['forearms'],
    light: ['front_delts'],
    instructions: [
      'Hold the roller in front of you with straight arms.',
      'Roll the weight up by twisting the handle hand over hand.',
      'Roll it back down slowly.',
    ],
  },
]);
