import { defineExercises } from '../define.ts';

export const back = defineExercises([
  // ─── Vertical pulls ───
  {
    name: 'Pull-up',
    aliases: ['pullup', 'overhand pull-up', 'weighted pull-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'weighted_bodyweight',
    rankKey: 'pullUp',
    met: 6,
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    light: ['forearms', 'rear_delts'],
    instructions: [
      'Hang from a bar with an overhand grip a little wider than your shoulders.',
      'Pull your shoulder blades down, then pull until your chin is over the bar.',
      'Lower all the way to straight arms.',
    ],
    tips: ['Log added weight from a belt or vest; leave it at 0 for bodyweight.'],
    mistakes: ['Half reps that never reach straight arms.', 'Kicking and swinging.'],
  },
  {
    name: 'Chin-up',
    aliases: ['chinup', 'underhand pull-up', 'supinated pull-up', 'weighted chin-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'weighted_bodyweight',
    rankKey: 'chinUp',
    met: 6,
    primary: ['lats', 'biceps'],
    secondary: ['upper_back'],
    light: ['forearms'],
    instructions: [
      'Hang from a bar with an underhand grip about shoulder width apart.',
      'Pull until your chin clears the bar.',
      'Lower slowly to straight arms.',
    ],
    tips: ['Log added weight from a belt or vest; leave it at 0 for bodyweight.'],
    mistakes: ['Craning your neck to get your chin over.'],
  },
  {
    name: 'Neutral-grip pull-up',
    aliases: ['hammer grip pull-up', 'parallel grip pull-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'weighted_bodyweight',
    met: 6,
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    light: ['forearms'],
    instructions: [
      'Hang from parallel handles with palms facing each other.',
      'Pull until your chin is over the handles.',
      'Lower to straight arms.',
    ],
  },
  {
    name: 'Wide-grip pull-up',
    aliases: ['wide pull-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'weighted_bodyweight',
    met: 6,
    primary: ['lats'],
    secondary: ['upper_back'],
    light: ['biceps', 'rear_delts'],
    instructions: [
      'Hang with an overhand grip well outside shoulder width.',
      'Pull your chest towards the bar.',
      'Lower under control.',
    ],
  },
  {
    name: 'Assisted pull-up machine',
    aliases: ['assisted pull-up', 'gravitron', 'assisted chin-up'],
    category: 'calisthenics',
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'assisted_bodyweight',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    instructions: [
      'Set the assistance weight and kneel or stand on the platform.',
      'Grip the handles and pull until your chin is over them.',
      'Lower slowly to straight arms.',
    ],
    tips: ['Log the assistance; less assistance means you’re getting stronger.'],
  },
  {
    name: 'Band-assisted pull-up',
    aliases: ['band pull-up', 'resistance band pull-up'],
    category: 'calisthenics',
    equipment: 'band',
    mechanic: 'compound',
    logType: 'assisted_bodyweight',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    instructions: [
      'Loop a band over the bar and put one foot or knee in it.',
      'Pull until your chin is over the bar.',
      'Lower slowly.',
    ],
    tips: ['Log the band’s rated assistance in kg if you know it.'],
  },
  {
    name: 'Lat pulldown',
    aliases: ['lat pull', 'lat pull down', 'pulldown', 'wide grip pulldown', 'front pulldown'],
    equipment: 'cable',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    light: ['rear_delts'],
    instructions: [
      'Sit with your thighs under the pads and grip the bar a little wider than shoulder width.',
      'Lean back slightly and pull the bar to your upper chest, driving your elbows down.',
      'Let the bar rise slowly until your arms are straight.',
    ],
    tips: ['Think about pulling your elbows into your back pockets.'],
    mistakes: ['Pulling the bar behind your neck.', 'Leaning way back and rowing it down.'],
  },
  {
    name: 'Close-grip lat pulldown',
    aliases: ['v bar pulldown', 'close grip pulldown', 'narrow grip lat pull'],
    equipment: 'cable',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    instructions: [
      'Attach a V-handle and sit with your thighs locked under the pads.',
      'Pull the handle to your upper chest.',
      'Return slowly to a full stretch.',
    ],
  },
  {
    name: 'Reverse-grip lat pulldown',
    aliases: ['underhand pulldown', 'supinated pulldown', 'reverse grip lat pull'],
    equipment: 'cable',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['lats'],
    secondary: ['biceps'],
    light: ['upper_back'],
    instructions: [
      'Grip the bar underhand at shoulder width.',
      'Pull it to your upper chest, elbows driving down and back.',
      'Return slowly.',
    ],
  },
  {
    name: 'Single-arm lat pulldown',
    aliases: ['one arm pulldown', 'single arm lat pull'],
    equipment: 'cable',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['lats'],
    secondary: ['biceps'],
    instructions: [
      'Attach a single handle to a high pulley and kneel or sit beneath it.',
      'Pull the handle down to the side of your chest.',
      'Return slowly and switch sides after the set.',
    ],
  },
  {
    name: 'Straight-arm cable pulldown',
    aliases: ['straight arm pulldown', 'lat prayer', 'cable pullover'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['lats'],
    light: ['triceps', 'rear_delts'],
    instructions: [
      'Stand facing a high pulley holding a bar or rope with straight arms.',
      'Hinge slightly and sweep the bar down to your thighs, keeping your arms straight.',
      'Let it rise slowly back to eye level.',
    ],
  },
  // ─── Rows ───
  {
    name: 'Barbell bent-over row',
    aliases: ['barbell row', 'bent over row', 'bb row', 'bor'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'barbellRow',
    met: 6,
    primary: ['lats', 'upper_back'],
    secondary: ['biceps', 'traps', 'rear_delts'],
    light: ['lower_back', 'forearms'],
    instructions: [
      'Hold the bar overhand, hinge forward until your torso is around 45° or lower, knees soft.',
      'Pull the bar to your lower ribs, squeezing your shoulder blades together.',
      'Lower it under control until your arms are straight.',
    ],
    mistakes: ['Standing up taller with every rep.', 'Jerking the weight with your lower back.'],
  },
  {
    name: 'Pendlay row',
    aliases: ['dead stop row'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 6,
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts'],
    light: ['lower_back'],
    instructions: [
      'Set your torso parallel to the floor with the bar resting on the ground.',
      'Row the bar explosively to your lower chest.',
      'Return it to the floor and reset before the next rep.',
    ],
  },
  {
    name: 'One-arm dumbbell row',
    aliases: ['dumbbell row', 'db row', 'single arm row', 'one arm row'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'dumbbellRow',
    unilateral: true,
    primary: ['lats', 'upper_back'],
    secondary: ['biceps', 'rear_delts'],
    instructions: [
      'Put one hand and knee on a bench, holding a dumbbell in the other hand.',
      'Row the dumbbell towards your hip, keeping your back flat.',
      'Lower to a full stretch and switch sides after the set.',
    ],
    mistakes: ['Twisting your torso to lift the weight.'],
  },
  {
    name: 'Chest-supported dumbbell row',
    aliases: ['incline dumbbell row', 'chest supported row'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['upper_back', 'lats'],
    secondary: ['rear_delts', 'biceps'],
    instructions: [
      'Lie chest-down on an incline bench with a dumbbell in each hand.',
      'Row the dumbbells up, squeezing your shoulder blades together.',
      'Lower to straight arms.',
    ],
    tips: ['Takes the lower back out of the movement.'],
  },
  {
    name: 'T-bar row',
    aliases: ['tbar row', 'landmine row'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts', 'traps'],
    light: ['lower_back'],
    instructions: [
      'Straddle the bar (or use the T-bar station) and grip the handle.',
      'Hinge forward with a flat back and row the weight to your chest.',
      'Lower under control.',
    ],
  },
  {
    name: 'Seated cable row',
    aliases: ['cable row', 'seated row', 'v bar row', 'low row', 'close grip cable row'],
    equipment: 'cable',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['lats', 'upper_back'],
    secondary: ['biceps', 'rear_delts'],
    instructions: [
      'Sit with your feet on the platform, knees soft, holding a V-handle.',
      'Sit tall and pull the handle to your belly, squeezing your shoulder blades.',
      'Let your arms straighten and shoulders reach forward slightly.',
    ],
    mistakes: ['Rocking back and forth to move the weight.'],
  },
  {
    name: 'Wide-grip seated cable row',
    aliases: ['wide cable row', 'wide grip row'],
    equipment: 'cable',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['upper_back'],
    secondary: ['rear_delts', 'lats'],
    light: ['biceps'],
    instructions: [
      'Attach a long bar and grip it wide and overhand.',
      'Pull the bar to your lower chest with elbows flared about 45°.',
      'Return slowly.',
    ],
  },
  {
    name: 'Single-arm seated cable row',
    aliases: ['one arm cable row'],
    equipment: 'cable',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['lats'],
    secondary: ['upper_back', 'biceps'],
    instructions: [
      'Sit at the row station with a single handle.',
      'Row the handle towards your hip without twisting.',
      'Return to a full stretch and switch sides after the set.',
    ],
  },
  {
    name: 'Chest-supported machine row',
    aliases: ['machine row', 'seated row machine', 'iso row'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['upper_back', 'lats'],
    secondary: ['rear_delts', 'biceps'],
    instructions: [
      'Set the chest pad so you can just reach the handles with straight arms.',
      'Row the handles back, squeezing your shoulder blades.',
      'Return slowly.',
    ],
  },
  {
    name: 'Smith machine row',
    aliases: ['smith row', 'smith bent over row'],
    equipment: 'smith',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['lats', 'upper_back'],
    secondary: ['biceps', 'rear_delts'],
    light: ['lower_back'],
    instructions: [
      'Set the Smith bar around knee height, grip it overhand and hinge forward.',
      'Row the bar to your lower ribs.',
      'Lower under control.',
    ],
  },
  // ─── Deadlifts and lower back ───
  {
    name: 'Barbell deadlift',
    aliases: ['deadlift', 'conventional deadlift', 'dl'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'deadlift',
    met: 6,
    primary: ['glutes', 'hamstrings', 'lower_back'],
    secondary: ['quads', 'traps'],
    light: ['forearms', 'upper_back', 'lats'],
    instructions: [
      'Stand with the bar over your mid-foot, feet hip width apart.',
      'Hinge down and grip the bar just outside your legs, then bend your knees until your shins touch it.',
      'Brace, flatten your back and push the floor away, keeping the bar close to your legs.',
      'Stand tall with hips and knees locked, then lower the bar the same way.',
    ],
    tips: [
      'Take the slack out of the bar before you pull.',
      'Use straps or chalk when grip limits you.',
    ],
    mistakes: [
      'Rounding the lower back.',
      'Letting the bar drift away from your legs.',
      'Leaning back hard at the top.',
    ],
  },
  {
    name: 'Sumo deadlift',
    aliases: ['sumo', 'sumo dl'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'sumoDeadlift',
    met: 6,
    primary: ['glutes', 'quads', 'adductors'],
    secondary: ['hamstrings', 'lower_back', 'traps'],
    light: ['forearms'],
    instructions: [
      'Take a wide stance with toes turned out and the bar over your mid-foot.',
      'Grip the bar inside your knees with straight arms.',
      'Push your knees out, brace and stand up by driving the floor apart.',
      'Lower the bar the same way.',
    ],
    mistakes: ['Hips shooting up first.', 'Knees caving in.'],
  },
  {
    name: 'Trap bar deadlift',
    aliases: ['hex bar deadlift', 'trap bar', 'hex bar'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'trapBarDeadlift',
    met: 6,
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'lower_back', 'traps'],
    light: ['forearms'],
    instructions: [
      'Stand in the middle of the trap bar and grip the handles.',
      'Sit your hips down, brace and keep your chest up.',
      'Drive through your legs to stand tall, then lower under control.',
    ],
    tips: ['Easier to learn than a straight-bar deadlift and kinder to the lower back.'],
  },
  {
    name: 'Rack pull',
    aliases: ['block pull', 'partial deadlift'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 6,
    primary: ['lower_back', 'glutes', 'traps'],
    secondary: ['upper_back', 'hamstrings'],
    light: ['forearms'],
    instructions: [
      'Set the bar on the safeties just below or above your knees.',
      'Grip it, brace and pull to a full lockout.',
      'Lower it back to the pins under control.',
    ],
  },
  {
    name: 'Back extension',
    aliases: ['hyperextension', '45 degree back extension', 'roman chair back extension'],
    equipment: 'bodyweight',
    category: 'calisthenics',
    mechanic: 'compound',
    logType: 'weighted_bodyweight',
    primary: ['lower_back', 'glutes'],
    secondary: ['hamstrings'],
    instructions: [
      'Set the pad just below your hips and hook your ankles in.',
      'Lower your torso by bending at the hips.',
      'Raise back up until your body is in a straight line.',
    ],
    tips: ['Hold a plate to your chest to add weight and log it as added weight.'],
    mistakes: ['Over-arching at the top.'],
  },
  {
    name: 'Reverse hyperextension',
    aliases: ['reverse hyper'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['glutes', 'lower_back'],
    secondary: ['hamstrings'],
    instructions: [
      'Lie face down on the reverse hyper with your hips at the edge of the pad.',
      'Swing your legs up until they’re in line with your body.',
      'Lower under control.',
    ],
  },
  {
    name: 'Superman',
    aliases: ['superman hold', 'prone extension'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    primary: ['lower_back'],
    light: ['glutes'],
    instructions: [
      'Lie face down with arms stretched overhead.',
      'Lift your arms, chest and legs off the floor together.',
      'Hold briefly, then lower.',
    ],
  },
  // ─── Traps ───
  {
    name: 'Barbell shrug',
    aliases: ['shrug', 'shrugs', 'bb shrug'],
    equipment: 'barbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['traps'],
    light: ['forearms'],
    instructions: [
      'Stand holding a barbell in front of your thighs.',
      'Shrug your shoulders straight up towards your ears.',
      'Hold briefly and lower.',
    ],
    mistakes: ['Rolling the shoulders in circles.', 'Bending the elbows.'],
  },
  {
    name: 'Dumbbell shrug',
    aliases: ['db shrug'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['traps'],
    light: ['forearms'],
    instructions: [
      'Stand holding dumbbells at your sides.',
      'Shrug your shoulders straight up.',
      'Lower slowly.',
    ],
  },
  // ─── Neck (optional muscle) ───
  {
    name: 'Plate neck flexion',
    aliases: ['neck curl', 'lying neck curl'],
    equipment: 'other',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['neck'],
    instructions: [
      'Lie face up on a bench with your head off the end and a light padded plate on your forehead.',
      'Curl your chin towards your chest.',
      'Lower slowly.',
    ],
    tips: ['Start very light and progress slowly.'],
  },
  {
    name: 'Plate neck extension',
    aliases: ['neck extension', 'lying neck extension'],
    equipment: 'other',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['neck'],
    instructions: [
      'Lie face down on a bench with your head off the end and a light padded plate on the back of your head.',
      'Raise your head until you’re looking forward.',
      'Lower slowly.',
    ],
    tips: ['Start very light and progress slowly.'],
  },
]);
