import { defineExercises } from '../define.ts';

/** Push-up progressions, dips, bodyweight pulls and legs. Static skills live in skills.ts. */
export const calisthenics = defineExercises([
  // ─── Push-up progressions (easiest first) ───
  {
    name: 'Wall push-up',
    aliases: ['wall pushup'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 3,
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    instructions: [
      'Stand an arm’s length from a wall and place your hands on it at chest height.',
      'Bend your elbows to bring your chest towards the wall.',
      'Push back to straight arms.',
    ],
    tips: ['Step further from the wall to make it harder.'],
  },
  {
    name: 'Incline push-up',
    aliases: ['incline pushup', 'elevated push-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    stabiliser: ['abs'],
    instructions: [
      'Place your hands on a bench or box, body straight from head to heels.',
      'Lower your chest to the edge.',
      'Push back up.',
    ],
  },
  {
    name: 'Knee push-up',
    aliases: ['kneeling push-up', 'knee pushup'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    instructions: [
      'Start on your hands and knees, hands a little wider than your shoulders.',
      'Keep a straight line from knees to head and lower your chest to the floor.',
      'Push back up.',
    ],
  },
  {
    name: 'Push-up',
    aliases: ['pushup', 'press-up', 'weighted push-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'weighted_bodyweight',
    rankKey: 'pushUp',
    met: 3.8,
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    stabiliser: ['abs'],
    instructions: [
      'Start in a high plank with hands slightly wider than your shoulders.',
      'Lower your chest to just above the floor, elbows about 45° from your body.',
      'Push back up to straight arms, keeping your body in one line.',
    ],
    tips: ['Add a weight plate on your back or a vest and log it as added weight.'],
    mistakes: ['Hips sagging.', 'Only going halfway down.', 'Flaring the elbows straight out.'],
  },
  {
    name: 'Wide push-up',
    aliases: ['wide grip push-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['mid_lower_chest'],
    secondary: ['front_delts'],
    light: ['triceps'],
    instructions: [
      'Set your hands well outside shoulder width.',
      'Lower your chest to the floor.',
      'Push back up.',
    ],
  },
  {
    name: 'Diamond push-up',
    aliases: ['close grip push-up', 'triangle push-up', 'tricep push-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['triceps'],
    secondary: ['mid_lower_chest', 'front_delts'],
    instructions: [
      'Place your hands together under your chest, thumbs and index fingers forming a diamond.',
      'Lower your chest to your hands, elbows close to your sides.',
      'Push back up.',
    ],
  },
  {
    name: 'Decline push-up',
    aliases: ['feet elevated push-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['upper_chest'],
    secondary: ['front_delts', 'triceps'],
    instructions: [
      'Put your feet on a bench and hands on the floor.',
      'Lower your chest to the floor.',
      'Push back up.',
    ],
  },
  {
    name: 'Archer push-up',
    aliases: ['archer pushup'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 4.5,
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    instructions: [
      'Set your hands very wide.',
      'Lower towards one hand while the other arm straightens out to the side.',
      'Push back up and alternate sides.',
    ],
    tips: ['A step towards the one-arm push-up.'],
  },
  {
    name: 'Pseudo planche push-up',
    aliases: ['ppp', 'planche push-up lean'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 4.5,
    primary: ['front_delts', 'mid_lower_chest'],
    secondary: ['triceps'],
    stabiliser: ['abs'],
    instructions: [
      'Start in a push-up with fingers turned out and hands beside your waist.',
      'Lean forward until your shoulders are well in front of your hands.',
      'Do push-ups while keeping that lean.',
    ],
  },
  {
    name: 'One-arm push-up',
    aliases: ['single arm push-up', 'one arm pushup'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    unilateral: true,
    met: 4.5,
    primary: ['mid_lower_chest', 'triceps'],
    secondary: ['front_delts'],
    stabiliser: ['obliques'],
    instructions: [
      'Take a wide stance and place one hand under your chest, the other behind your back.',
      'Lower your chest towards the floor without twisting.',
      'Push back up. Switch arms after the set.',
    ],
  },
  {
    name: 'Clap push-up',
    aliases: ['plyo push-up', 'explosive push-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 8,
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    instructions: [
      'Lower into a push-up.',
      'Push up explosively so your hands leave the floor and clap.',
      'Land softly and go straight into the next rep.',
    ],
  },
  {
    name: 'Hindu push-up',
    aliases: ['dand', 'dands', 'hindu pushup'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 4.5,
    primary: ['front_delts', 'mid_lower_chest'],
    secondary: ['triceps'],
    light: ['lower_back'],
    instructions: [
      'Start in downward dog: hands and feet on the floor, hips high.',
      'Swoop your chest down close to the floor and forward between your hands, ending with arms straight and chest up.',
      'Push your hips back up to the start.',
    ],
    tips: ['A traditional akhara exercise; keep it smooth and rhythmic.'],
  },
  {
    name: 'Pike push-up',
    aliases: ['pike pushup'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 4.5,
    primary: ['front_delts'],
    secondary: ['triceps'],
    light: ['upper_chest'],
    instructions: [
      'Start in a downward dog with hips high and hands shoulder width.',
      'Bend your elbows to lower the top of your head towards the floor in front of your hands.',
      'Push back up.',
    ],
    tips: ['Raise your feet on a box to make it harder; it builds towards handstand push-ups.'],
  },
  // ─── Dips ───
  {
    name: 'Parallel bar dip',
    aliases: ['dip', 'dips', 'chest dip', 'tricep dip', 'weighted dip'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'weighted_bodyweight',
    rankKey: 'dip',
    met: 5,
    primary: ['mid_lower_chest', 'triceps'],
    secondary: ['front_delts'],
    instructions: [
      'Support yourself on parallel bars with straight arms.',
      'Lower until your shoulders are just below your elbows.',
      'Press back up to straight arms.',
    ],
    tips: [
      'Log added weight from a belt; leave it at 0 for bodyweight.',
      'Lean forward for more chest.',
    ],
    mistakes: ['Shrugging your shoulders up towards your ears.', 'Going too deep too soon.'],
  },
  {
    name: 'Assisted dip machine',
    aliases: ['assisted dip'],
    category: 'calisthenics',
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'assisted_bodyweight',
    primary: ['mid_lower_chest', 'triceps'],
    secondary: ['front_delts'],
    instructions: [
      'Set the assistance and kneel on the pad, gripping the dip handles.',
      'Lower until your shoulders are just below your elbows.',
      'Press back up.',
    ],
  },
  {
    name: 'Ring dip',
    aliases: ['rings dip'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'weighted_bodyweight',
    met: 5,
    primary: ['mid_lower_chest', 'triceps'],
    secondary: ['front_delts'],
    stabiliser: ['biceps'],
    instructions: [
      'Support yourself on gymnastic rings with straight arms, rings turned out.',
      'Lower until your shoulders are below your elbows, keeping the rings close.',
      'Press back up and turn the rings out at the top.',
    ],
  },
  {
    name: 'Straight bar dip',
    aliases: ['single bar dip'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 5,
    primary: ['triceps', 'mid_lower_chest'],
    secondary: ['front_delts'],
    instructions: [
      'Support yourself on top of a straight bar with your hips touching it.',
      'Lean forward and lower your chest towards the bar.',
      'Press back up. This is the top half of a muscle-up.',
    ],
  },
  // ─── Pulls ───
  {
    name: 'Inverted row',
    aliases: ['australian pull-up', 'bodyweight row', 'body row'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 4,
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts'],
    instructions: [
      'Hang under a bar set at waist height, body straight and heels on the floor.',
      'Pull your chest up to the bar.',
      'Lower to straight arms.',
    ],
    tips: ['Walk your feet forward or raise them to make it harder.'],
  },
  {
    name: 'Negative pull-up',
    aliases: ['pull-up negative', 'eccentric pull-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 5,
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    instructions: [
      'Jump or step up so your chin is over the bar.',
      'Lower yourself as slowly as you can, aiming for 3–5 seconds.',
      'Step down and repeat.',
    ],
    tips: ['The fastest route to your first pull-up.'],
  },
  {
    name: 'Scapular pull-up',
    aliases: ['scap pull-up', 'scap pulls'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 3,
    primary: ['lats'],
    secondary: ['traps'],
    instructions: [
      'Hang from a bar with straight arms.',
      'Pull your shoulder blades down and back to lift your body slightly, arms still straight.',
      'Relax back into the hang.',
    ],
  },
  {
    name: 'Archer pull-up',
    aliases: ['archer pullup'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 6,
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    instructions: [
      'Hang with a very wide grip.',
      'Pull towards one hand while the other arm straightens along the bar.',
      'Lower and alternate sides.',
    ],
  },
  {
    name: 'L-sit pull-up',
    aliases: ['l pull-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 6,
    primary: ['lats', 'abs'],
    secondary: ['biceps'],
    instructions: [
      'Hang from a bar and lift your straight legs to hip height.',
      'Pull up while holding the L shape.',
      'Lower with your legs still raised.',
    ],
  },
  {
    name: 'Muscle-up',
    aliases: ['bar muscle-up', 'muscleup'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    rankKey: 'muscleUp',
    met: 8,
    primary: ['lats', 'triceps'],
    secondary: ['mid_lower_chest', 'biceps', 'front_delts'],
    stabiliser: ['abs'],
    instructions: [
      'Hang from a bar with a false or overhand grip.',
      'Pull explosively to your lower chest while leaning your shoulders over the bar.',
      'Turn your wrists over and press up to straight arms on top of the bar.',
      'Lower back down under control.',
    ],
    tips: ['Build up to 10+ strict pull-ups and 15+ straight bar dips first.'],
    mistakes: ['Chicken-winging one arm over at a time.'],
  },
  {
    name: 'Ring muscle-up',
    aliases: ['rings muscle-up'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 8,
    primary: ['lats', 'triceps'],
    secondary: ['mid_lower_chest', 'biceps'],
    stabiliser: ['abs'],
    instructions: [
      'Hang from rings with a false grip.',
      'Pull the rings to your chest, then transition your chest over them.',
      'Press out of the dip to straight arms.',
    ],
  },
  {
    name: 'Dead hang',
    aliases: ['bar hang', 'passive hang'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    met: 2.5,
    primary: ['forearms'],
    light: ['lats'],
    instructions: [
      'Grip a pull-up bar with straight arms and let your feet come off the floor.',
      'Relax your shoulders and hang.',
      'Hold for time.',
    ],
    tips: ['Good for grip strength and decompressing the spine.'],
  },
  // ─── Legs ───
  {
    name: 'Bodyweight squat',
    aliases: ['air squat', 'squats bodyweight', 'free squat'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 5,
    primary: ['quads', 'glutes'],
    light: ['adductors'],
    instructions: [
      'Stand with feet shoulder width apart, arms out in front.',
      'Squat down until your thighs are at least parallel.',
      'Stand back up.',
    ],
  },
  {
    name: 'Hindu squat',
    aliases: ['baithak', 'baithaks', 'bethak'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 5,
    primary: ['quads'],
    secondary: ['calves', 'glutes'],
    instructions: [
      'Stand with feet hip width apart and arms forward.',
      'Squat down onto the balls of your feet, heels lifting, as your arms swing back.',
      'Rise up, swinging your arms forward, in one smooth rhythm.',
    ],
    tips: ['Traditionally done for high reps with dands.'],
  },
  {
    name: 'Jump squat',
    aliases: ['squat jump', 'jumping squat'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 8,
    primary: ['quads', 'glutes'],
    secondary: ['calves'],
    instructions: [
      'Squat down to about parallel.',
      'Jump up explosively.',
      'Land softly and sink straight into the next squat.',
    ],
  },
  {
    name: 'Bodyweight lunge',
    aliases: ['lunge', 'alternating lunge'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    unilateral: true,
    met: 4,
    primary: ['quads', 'glutes'],
    light: ['adductors'],
    instructions: [
      'Step forward and lower until both knees are bent at about 90°.',
      'Push back to standing.',
      'Alternate legs.',
    ],
  },
  {
    name: 'Box pistol squat',
    aliases: ['assisted pistol', 'pistol to box'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    unilateral: true,
    met: 4.5,
    primary: ['quads', 'glutes'],
    stabiliser: ['abductors'],
    instructions: [
      'Stand on one leg in front of a box with the other leg held out in front.',
      'Sit back onto the box on one leg.',
      'Stand back up without the other foot touching down. Switch legs after the set.',
    ],
    tips: ['Lower the box over time until you reach a full pistol.'],
  },
  {
    name: 'Pistol squat',
    aliases: ['pistol', 'single leg squat', 'one leg squat'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'weighted_bodyweight',
    rankKey: 'pistolSquat',
    unilateral: true,
    met: 5,
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    stabiliser: ['abductors', 'abs'],
    instructions: [
      'Stand on one leg with the other leg held straight out in front.',
      'Squat all the way down on the standing leg, keeping the heel down.',
      'Stand back up without touching the free foot down. Switch legs after the set.',
    ],
    tips: ['Hold a small weight out in front to help balance.'],
  },
  {
    name: 'Shrimp squat',
    aliases: ['shrimp'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    unilateral: true,
    met: 5,
    primary: ['quads'],
    secondary: ['glutes'],
    instructions: [
      'Stand on one leg and hold the other foot behind you.',
      'Lower until your back knee touches the floor.',
      'Stand back up. Switch legs after the set.',
    ],
  },
  {
    name: 'Cossack squat',
    aliases: ['cossack'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 4,
    primary: ['adductors', 'quads'],
    secondary: ['glutes'],
    instructions: [
      'Take a very wide stance.',
      'Shift to one side and sit deep into that leg while the other stays straight, toes up.',
      'Move through the middle to the other side.',
    ],
  },
  {
    name: 'Nordic hamstring curl',
    aliases: ['nordic curl', 'nordics', 'nordic'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 4,
    primary: ['hamstrings'],
    light: ['glutes'],
    instructions: [
      'Kneel with your heels anchored under a pad or held by a partner.',
      'Keeping your hips straight, lower your body forward as slowly as you can.',
      'Catch yourself with your hands and push back up.',
    ],
    tips: ['Excellent for preventing hamstring injuries.'],
  },
  {
    name: 'Wall sit',
    aliases: ['wall squat'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    met: 3.5,
    primary: ['quads'],
    light: ['glutes'],
    instructions: [
      'Lean your back against a wall and slide down until your thighs are parallel to the floor.',
      'Keep your knees over your ankles.',
      'Hold for time.',
    ],
  },
  {
    name: 'Bodyweight calf raise',
    aliases: ['calf raise bodyweight', 'standing calf raise bodyweight'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 2.8,
    primary: ['calves'],
    instructions: [
      'Stand on a step with your heels hanging off.',
      'Lower your heels, then rise high onto your toes.',
      'Repeat slowly.',
    ],
  },
]);
