import { defineExercises } from '../define.ts';

export const cardio = defineExercises([
  {
    name: 'Treadmill run',
    aliases: ['treadmill', 'running treadmill', 'jogging'],
    category: 'cardio',
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'distance_duration',
    met: 9.8,
    primary: ['quads', 'calves'],
    secondary: ['hamstrings', 'glutes'],
    instructions: [
      'Start walking to warm up, then raise the speed to a steady run.',
      'Run tall with relaxed shoulders and short, quick steps.',
      'Cool down with a few minutes of walking.',
    ],
  },
  {
    name: 'Outdoor run',
    aliases: ['run', 'running', 'jog'],
    category: 'cardio',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'distance_duration',
    met: 9.8,
    primary: ['quads', 'calves'],
    secondary: ['hamstrings', 'glutes'],
    instructions: [
      'Warm up with brisk walking or an easy jog.',
      'Run at a pace you can hold for the planned distance or time.',
      'Cool down with walking.',
    ],
    tips: ['Most of your weekly runs should feel easy enough to talk.'],
  },
  {
    name: 'Incline treadmill walk',
    aliases: ['incline walk', '12-3-30', 'treadmill incline walking'],
    category: 'cardio',
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'distance_duration',
    met: 6,
    primary: ['glutes', 'calves'],
    secondary: ['hamstrings', 'quads'],
    instructions: [
      'Set the treadmill to a steep incline (10–15%) and a brisk walking speed.',
      'Walk without holding the handrails.',
      'Keep going for the planned time.',
    ],
    mistakes: ['Hanging on to the handrails.'],
  },
  {
    name: 'Walking',
    aliases: ['walk', 'brisk walk', 'steps'],
    category: 'cardio',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'distance_duration',
    met: 3.5,
    primary: ['calves'],
    light: ['quads', 'glutes'],
    instructions: [
      'Walk at a brisk pace where you breathe a little harder but can still talk.',
      'Keep going for the planned distance or time.',
    ],
  },
  {
    name: 'Stationary bike',
    aliases: ['exercise bike', 'cycling indoor', 'spin bike', 'cycle'],
    category: 'cardio',
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'distance_duration',
    met: 7,
    primary: ['quads'],
    secondary: ['glutes', 'calves'],
    light: ['hamstrings'],
    instructions: [
      'Set the seat so your knee is slightly bent at the bottom of each pedal stroke.',
      'Pedal at a steady cadence and resistance.',
      'Cool down with easy pedalling.',
    ],
  },
  {
    name: 'Outdoor cycling',
    aliases: ['cycling', 'bike ride', 'road cycling'],
    category: 'cardio',
    equipment: 'other',
    mechanic: 'compound',
    logType: 'distance_duration',
    met: 7.5,
    primary: ['quads'],
    secondary: ['glutes', 'calves'],
    light: ['hamstrings'],
    instructions: [
      'Check your brakes and wear a helmet.',
      'Ride at a steady effort for the planned distance or time.',
    ],
  },
  {
    name: 'Rowing machine',
    aliases: ['rower', 'erg', 'indoor rowing', 'concept2'],
    category: 'cardio',
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'distance_duration',
    met: 7,
    primary: ['quads', 'upper_back'],
    secondary: ['lats', 'glutes', 'hamstrings'],
    light: ['biceps'],
    instructions: [
      'Strap your feet in and grip the handle with straight arms.',
      'Drive with your legs first, then lean back slightly and pull the handle to your lower ribs.',
      'Return in reverse order: arms, body, then legs.',
    ],
    tips: ['Think legs, body, arms on the drive; arms, body, legs on the way back.'],
  },
  {
    name: 'Elliptical',
    aliases: ['cross trainer', 'elliptical trainer'],
    category: 'cardio',
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'distance_duration',
    met: 5,
    primary: ['quads', 'glutes'],
    light: ['hamstrings', 'calves'],
    instructions: [
      'Step on and hold the moving handles.',
      'Stride smoothly, pushing and pulling the handles.',
      'Keep a steady pace for the planned time.',
    ],
  },
  {
    name: 'Stair climber',
    aliases: ['stairmaster', 'stair machine', 'step mill'],
    category: 'cardio',
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'duration',
    met: 9,
    primary: ['glutes', 'quads'],
    secondary: ['calves'],
    instructions: [
      'Step on and set a pace you can sustain.',
      'Climb tall with light hands on the rails.',
      'Keep going for the planned time.',
    ],
  },
  {
    name: 'Jump rope',
    aliases: ['skipping', 'skipping rope', 'skip rope'],
    category: 'cardio',
    equipment: 'other',
    mechanic: 'compound',
    logType: 'duration',
    met: 11,
    primary: ['calves'],
    secondary: ['quads'],
    light: ['forearms', 'front_delts'],
    instructions: [
      'Hold the handles with elbows close to your sides.',
      'Turn the rope with your wrists and hop just high enough to clear it.',
      'Land softly on the balls of your feet.',
    ],
  },
  {
    name: 'Swimming',
    aliases: ['swim', 'laps'],
    category: 'cardio',
    equipment: 'other',
    mechanic: 'compound',
    logType: 'distance_duration',
    met: 8,
    primary: ['lats', 'front_delts'],
    secondary: ['triceps', 'quads'],
    instructions: [
      'Warm up with easy lengths.',
      'Swim at a steady pace for the planned distance or time.',
    ],
  },
  {
    name: 'Air bike',
    aliases: ['assault bike', 'fan bike', 'echo bike'],
    category: 'cardio',
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'distance_duration',
    met: 10,
    primary: ['quads'],
    secondary: ['glutes', 'front_delts'],
    light: ['triceps'],
    instructions: [
      'Set the seat height and grip the moving handles.',
      'Push and pull with your arms while you pedal.',
      'Go hard for intervals or steady for longer efforts.',
    ],
  },
  {
    name: 'Jumping jacks',
    aliases: ['star jumps', 'jumping jack'],
    category: 'cardio',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 8,
    primary: ['calves'],
    secondary: ['side_delts', 'abductors'],
    instructions: [
      'Stand with feet together and arms at your sides.',
      'Jump your feet out while raising your arms overhead.',
      'Jump back to the start and keep going.',
    ],
  },
  {
    name: 'High knees',
    aliases: ['high knee run'],
    category: 'cardio',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 8,
    primary: ['quads'],
    secondary: ['abs', 'calves'],
    instructions: [
      'Run on the spot, driving each knee up to hip height.',
      'Pump your arms and stay on the balls of your feet.',
      'Keep going for the set time.',
    ],
  },
]);

export const mobility = defineExercises([
  {
    name: 'Surya namaskar',
    aliases: ['sun salutation', 'suryanamaskar'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 3.5,
    primary: ['hamstrings', 'front_delts'],
    secondary: ['lower_back', 'abs'],
    instructions: [
      'Stand tall, raise your arms overhead, then fold forward to your feet.',
      'Step back into a plank, lower down and lift your chest into cobra.',
      'Push back to downward dog, step forward and rise back to standing.',
      'Each full sequence counts as one rep.',
    ],
  },
  {
    name: 'Downward dog',
    aliases: ['adho mukha svanasana', 'down dog'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    primary: ['hamstrings', 'calves'],
    secondary: ['lats'],
    instructions: [
      'From hands and knees, lift your hips up and back into an upside-down V.',
      'Press your heels towards the floor and your chest towards your thighs.',
      'Hold and breathe.',
    ],
  },
  {
    name: 'Cobra stretch',
    aliases: ['bhujangasana', 'cobra'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    primary: ['abs'],
    light: ['lower_back'],
    instructions: [
      'Lie face down with hands under your shoulders.',
      'Press your chest up, keeping your hips on the floor.',
      'Hold and breathe.',
    ],
  },
  {
    name: "Child's pose",
    aliases: ['balasana', 'childs pose'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    primary: ['lower_back'],
    secondary: ['lats'],
    instructions: [
      'Kneel and sit back on your heels.',
      'Fold forward and reach your arms out in front on the floor.',
      'Relax and breathe.',
    ],
  },
  {
    name: 'Cat-cow',
    aliases: ['cat camel'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    primary: ['lower_back'],
    light: ['abs'],
    instructions: [
      'Start on hands and knees.',
      'Round your back up towards the ceiling, then let it sink as you lift your chest.',
      'Move slowly with your breath.',
    ],
  },
  {
    name: "World's greatest stretch",
    aliases: ['worlds greatest stretch', 'wgs'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    primary: ['glutes', 'hamstrings'],
    secondary: ['upper_back', 'adductors'],
    instructions: [
      'Step into a deep lunge and place the opposite hand on the floor.',
      'Drop your inside elbow towards your front foot, then rotate and reach that arm to the ceiling.',
      'Return and switch sides.',
    ],
  },
  {
    name: 'Couch stretch',
    aliases: ['hip flexor stretch', 'kneeling hip flexor stretch'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    unilateral: true,
    primary: ['quads'],
    instructions: [
      'Kneel with one shin up against a wall or bench behind you.',
      'Step the other foot forward into a lunge and squeeze the glute of the back leg.',
      'Hold, then switch sides.',
    ],
  },
  {
    name: 'Standing hamstring stretch',
    aliases: ['hamstring stretch', 'toe touch'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    primary: ['hamstrings'],
    instructions: [
      'Put one heel on a low step with the leg straight.',
      'Hinge forward from the hips with a flat back until you feel the stretch.',
      'Hold, then switch sides.',
    ],
  },
  {
    name: 'Pigeon stretch',
    aliases: ['pigeon pose', 'kapotasana'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    unilateral: true,
    primary: ['glutes'],
    instructions: [
      'From a plank, bring one knee forward behind your wrist with the shin angled across.',
      'Lower your hips towards the floor and fold forward over the front leg.',
      'Hold, then switch sides.',
    ],
  },
  {
    name: '90/90 hip switch',
    slug: 'hip-90-90-switch',
    aliases: ['90 90 stretch', 'ninety ninety'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    primary: ['glutes'],
    secondary: ['adductors'],
    instructions: [
      'Sit with both knees bent at 90°, one leg in front and one to the side.',
      'Rotate both knees over to the other side without using your hands.',
      'Keep switching slowly.',
    ],
  },
  {
    name: 'Butterfly stretch',
    aliases: ['groin stretch', 'baddha konasana'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    primary: ['adductors'],
    instructions: [
      'Sit with the soles of your feet together and knees out to the sides.',
      'Hold your feet and gently press your knees down.',
      'Hold and breathe.',
    ],
  },
  {
    name: 'Deep squat hold',
    aliases: ['malasana', 'squat hold', 'resting squat'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    primary: ['adductors', 'calves'],
    secondary: ['glutes'],
    instructions: [
      'Squat as deep as you can with heels on the floor.',
      'Use your elbows to press your knees out and keep your chest up.',
      'Hold and breathe.',
    ],
  },
  {
    name: 'Open book rotation',
    aliases: ['thoracic rotation', 'open book', 't-spine rotation'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    primary: ['upper_back'],
    light: ['mid_lower_chest'],
    instructions: [
      'Lie on your side with knees bent and arms stretched out together in front.',
      'Open the top arm over to the other side, following it with your eyes.',
      'Return and repeat, then switch sides.',
    ],
  },
  {
    name: 'Doorway chest stretch',
    aliases: ['chest stretch', 'pec stretch'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    primary: ['mid_lower_chest'],
    light: ['front_delts'],
    instructions: [
      'Place your forearm on a doorframe with your elbow at shoulder height.',
      'Step through the door until you feel a stretch across your chest.',
      'Hold, then switch sides.',
    ],
  },
  {
    name: 'Band shoulder dislocate',
    aliases: ['shoulder dislocates', 'pass through', 'band pass through'],
    category: 'mobility',
    equipment: 'band',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    primary: ['front_delts'],
    secondary: ['mid_lower_chest'],
    instructions: [
      'Hold a band or stick wide in front of your thighs.',
      'With straight arms, lift it over your head and behind you.',
      'Bring it back over to the front. Narrow your grip over time.',
    ],
  },
  {
    name: 'Overhead lat stretch',
    aliases: ['lat stretch'],
    category: 'mobility',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    primary: ['lats'],
    instructions: [
      'Hold a rack or doorframe at head height with one or both hands.',
      'Sit your hips back and let your chest sink until you feel the stretch along your sides.',
      'Hold and breathe.',
    ],
  },
]);
