import { defineExercises } from '../define.ts';

export const chest = defineExercises([
  {
    name: 'Barbell bench press',
    aliases: ['bench press', 'bench', 'flat bench', 'bb bench', 'chest press barbell'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'benchPress',
    met: 6,
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    light: ['upper_chest'],
    instructions: [
      'Lie on the bench with your eyes under the bar and feet flat on the floor.',
      'Grip the bar a little wider than shoulder width, squeeze your shoulder blades together and unrack.',
      'Lower the bar under control to your mid chest, elbows about 45–70° from your body.',
      'Press back up until your arms are straight, keeping your upper back tight on the bench.',
    ],
    tips: [
      'Keep a slight arch and drive your feet into the floor.',
      'Use a spotter or safety pins when going heavy.',
    ],
    mistakes: [
      'Bouncing the bar off your chest.',
      'Flaring the elbows straight out to the sides.',
      'Lifting your hips off the bench.',
    ],
  },
  {
    name: 'Paused bench press',
    aliases: ['pause bench', 'competition bench'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 6,
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    light: ['upper_chest'],
    instructions: [
      'Set up exactly as for a normal bench press.',
      'Lower the bar to your chest and hold it still for one to two seconds.',
      'Press up without losing tightness.',
    ],
    tips: ['Stay tight during the pause; don’t let the bar sink into your chest.'],
    mistakes: ['Relaxing at the bottom.', 'Cutting the pause short.'],
  },
  {
    name: 'Barbell incline bench press',
    aliases: ['incline bench', 'incline press', 'incline barbell press'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'inclineBench',
    met: 6,
    primary: ['upper_chest'],
    secondary: ['front_delts', 'triceps'],
    light: ['mid_lower_chest'],
    instructions: [
      'Set the bench to 30–45° and lie back with your eyes under the bar.',
      'Unrack with a grip slightly wider than shoulder width.',
      'Lower the bar to your upper chest, just below the collarbones.',
      'Press back up over your shoulders.',
    ],
    tips: ['A lower incline (around 30°) keeps more of the work on the chest.'],
    mistakes: [
      'Setting the bench so steep it becomes a shoulder press.',
      'Bouncing off the chest.',
    ],
  },
  {
    name: 'Barbell decline bench press',
    aliases: ['decline bench', 'decline press'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 6,
    primary: ['mid_lower_chest'],
    secondary: ['triceps'],
    light: ['front_delts'],
    instructions: [
      'Hook your legs into the decline bench and lie back.',
      'Unrack the bar with a slightly wider than shoulder-width grip.',
      'Lower it to your lower chest, then press back up.',
    ],
    tips: ['Have a spotter hand you the bar: unracking on a decline is awkward.'],
    mistakes: ['Letting the bar drift towards your neck.'],
  },
  {
    name: 'Close-grip bench press',
    aliases: ['cgbp', 'close grip bench', 'narrow grip bench'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'closeGripBench',
    met: 6,
    primary: ['triceps'],
    secondary: ['mid_lower_chest', 'front_delts'],
    instructions: [
      'Lie on a flat bench and grip the bar about shoulder width apart.',
      'Unrack and lower the bar to your lower chest, keeping elbows close to your sides.',
      'Press up by straightening your arms.',
    ],
    tips: ['Shoulder width is close enough; a very narrow grip strains the wrists.'],
    mistakes: ['Hands touching in the middle of the bar.', 'Elbows flaring out.'],
  },
  {
    name: 'Barbell floor press',
    aliases: ['floor press'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['mid_lower_chest', 'triceps'],
    secondary: ['front_delts'],
    instructions: [
      'Lie on the floor inside a rack with the bar set low, knees bent.',
      'Unrack and lower until your upper arms touch the floor.',
      'Pause briefly, then press back up.',
    ],
    tips: [
      'Great for lockout strength and for training around a shoulder that dislikes deep presses.',
    ],
    mistakes: ['Slamming the elbows into the floor.'],
  },
  {
    name: 'Dumbbell bench press',
    aliases: ['db bench', 'dumbbell chest press', 'flat dumbbell press', 'db press'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'dumbbellBench',
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    light: ['upper_chest'],
    instructions: [
      'Sit on a flat bench with the dumbbells on your thighs, then lie back and bring them to your chest.',
      'Press the dumbbells up until your arms are straight above your chest.',
      'Lower them slowly to the sides of your chest and press again.',
    ],
    tips: [
      'Log the weight of one dumbbell.',
      'Kick the dumbbells up with your knees to get into position.',
    ],
    mistakes: [
      'Dropping the dumbbells too fast at the bottom.',
      'Clanging them together at the top.',
    ],
  },
  {
    name: 'Incline dumbbell press',
    aliases: ['incline db press', 'incline dumbbell bench'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'inclineDumbbellBench',
    primary: ['upper_chest'],
    secondary: ['front_delts', 'triceps'],
    light: ['mid_lower_chest'],
    instructions: [
      'Set the bench to 30–45° and sit back with a dumbbell on each thigh.',
      'Bring them to shoulder level and press up over your upper chest.',
      'Lower slowly until you feel a stretch across the chest.',
    ],
    tips: ['Log the weight of one dumbbell.'],
    mistakes: ['Arching so much that it becomes a flat press.'],
  },
  {
    name: 'Decline dumbbell press',
    aliases: ['decline db press'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['mid_lower_chest'],
    secondary: ['triceps'],
    light: ['front_delts'],
    instructions: [
      'Secure your legs on a decline bench with a dumbbell in each hand.',
      'Press the dumbbells up over your lower chest.',
      'Lower them under control and repeat.',
    ],
    mistakes: ['Letting the dumbbells drift over your face.'],
  },
  {
    name: 'Dumbbell floor press',
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['mid_lower_chest', 'triceps'],
    secondary: ['front_delts'],
    instructions: [
      'Lie on the floor with knees bent and a dumbbell in each hand.',
      'Press the dumbbells up, then lower until your upper arms touch the floor.',
      'Pause and press again.',
    ],
    tips: ['A good home option when you don’t have a bench.'],
  },
  {
    name: 'Smith machine bench press',
    aliases: ['smith bench', 'smith flat press'],
    equipment: 'smith',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    instructions: [
      'Set a flat bench under the Smith bar so it lines up with your mid chest.',
      'Unhook the bar and lower it to your chest.',
      'Press back up and lock out, then re-hook when done.',
    ],
    tips: ['Set the safety stops just below chest height.'],
    mistakes: ['Bench too far forward or back, so the bar lands on your neck or belly.'],
  },
  {
    name: 'Smith machine incline press',
    aliases: ['smith incline', 'smith incline bench'],
    equipment: 'smith',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['upper_chest'],
    secondary: ['front_delts', 'triceps'],
    instructions: [
      'Place an incline bench (30–45°) under the Smith bar.',
      'Unhook and lower the bar to your upper chest.',
      'Press back up and re-hook at the end of the set.',
    ],
    mistakes: ['Bench angle too steep.'],
  },
  {
    name: 'Machine chest press',
    aliases: ['chest press', 'seated chest press', 'chest press machine'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    instructions: [
      'Adjust the seat so the handles line up with your mid chest.',
      'Grip the handles and press forward until your arms are straight.',
      'Return slowly until you feel a stretch in your chest.',
    ],
    tips: ['Keep your back against the pad throughout.'],
    mistakes: ['Seat set too high or too low.', 'Letting the stack slam between reps.'],
  },
  {
    name: 'Incline machine chest press',
    aliases: ['incline chest press', 'machine incline press'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['upper_chest'],
    secondary: ['front_delts', 'triceps'],
    instructions: [
      'Adjust the seat so the handles start around your upper chest.',
      'Press up and forward until your arms are straight.',
      'Lower slowly and repeat.',
    ],
  },
  {
    name: 'Plate-loaded chest press',
    aliases: ['hammer strength chest press', 'iso lateral chest press'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    instructions: [
      'Sit with the handles at mid-chest height and your back on the pad.',
      'Press the handles forward until your arms are straight.',
      'Lower slowly to a deep stretch.',
    ],
    tips: ['Log the total plates you added, not the machine’s starting weight.'],
  },
  {
    name: 'Dumbbell fly',
    aliases: ['db fly', 'flat fly', 'chest fly', 'dumbbell flye'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['mid_lower_chest'],
    light: ['front_delts', 'upper_chest'],
    instructions: [
      'Lie on a flat bench holding dumbbells above your chest, palms facing each other.',
      'With a slight bend in your elbows, open your arms in a wide arc until you feel a chest stretch.',
      'Bring the dumbbells back together over your chest.',
    ],
    tips: ['Think of hugging a big tree.'],
    mistakes: [
      'Bending the elbows so much it turns into a press.',
      'Going too heavy and too deep.',
    ],
  },
  {
    name: 'Incline dumbbell fly',
    aliases: ['incline fly', 'incline db fly'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['upper_chest'],
    light: ['front_delts'],
    instructions: [
      'Lie on a 30° incline bench with dumbbells above your chest.',
      'Open your arms in a wide arc with a soft bend in the elbows.',
      'Squeeze them back together over your upper chest.',
    ],
  },
  {
    name: 'Machine fly',
    aliases: [
      'pec deck',
      'pec dec',
      'butterfly',
      'butterfly machine',
      'pec fly',
      'chest fly machine',
    ],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['mid_lower_chest'],
    light: ['upper_chest', 'front_delts'],
    instructions: [
      'Adjust the seat so the handles are at chest height.',
      'Grip the handles (or press the pads) with a slight bend in the elbows.',
      'Bring them together in front of your chest and squeeze.',
      'Open back out slowly until you feel a stretch.',
    ],
    tips: ['Keep your chest up and shoulders back against the pad.'],
    mistakes: ['Letting the weight pull your shoulders forward at the back.'],
  },
  {
    name: 'Cable crossover',
    aliases: ['cable fly', 'high to low cable fly', 'crossover', 'cable chest fly'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['mid_lower_chest'],
    light: ['upper_chest', 'front_delts'],
    instructions: [
      'Set both pulleys high and take a handle in each hand with a split stance.',
      'Lean slightly forward with a soft bend in the elbows.',
      'Pull the handles down and together in front of your hips.',
      'Return slowly until your arms are out wide.',
    ],
    tips: ['Cross your hands slightly at the bottom for a stronger squeeze.'],
    mistakes: ['Pressing the handles instead of sweeping them in an arc.'],
  },
  {
    name: 'Low-to-high cable fly',
    aliases: ['low cable fly', 'upper chest cable fly', 'low to high crossover'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['upper_chest'],
    light: ['front_delts'],
    instructions: [
      'Set both pulleys low and hold a handle in each hand.',
      'Sweep your arms up and together to shoulder height.',
      'Lower back under control.',
    ],
  },
  {
    name: 'Cable chest press',
    aliases: ['standing cable press'],
    equipment: 'cable',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['mid_lower_chest'],
    secondary: ['triceps', 'front_delts'],
    stabiliser: ['abs'],
    instructions: [
      'Set the pulleys at chest height and stand in a split stance facing away.',
      'Press the handles forward until your arms are straight.',
      'Return slowly to a stretch.',
    ],
  },
  {
    name: 'Dumbbell pullover',
    aliases: ['db pullover', 'pullover'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['lats', 'mid_lower_chest'],
    light: ['triceps'],
    stabiliser: ['abs'],
    instructions: [
      'Lie across or along a bench holding one dumbbell with both hands above your chest.',
      'With slightly bent elbows, lower it back behind your head until you feel a stretch.',
      'Pull it back over your chest.',
    ],
    mistakes: ['Bending the elbows so it becomes a triceps extension.'],
  },
  {
    name: 'Svend press',
    aliases: ['plate squeeze press', 'plate press'],
    equipment: 'other',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['mid_lower_chest'],
    light: ['front_delts'],
    instructions: [
      'Stand holding one or two plates squeezed together between your palms at chest height.',
      'Press them straight out in front while squeezing hard.',
      'Bring them back to your chest.',
    ],
  },
]);
