import { defineExercises } from '../define.ts';

export const core = defineExercises([
  {
    name: 'Plank',
    aliases: ['front plank', 'forearm plank', 'elbow plank'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    met: 3.8,
    primary: ['abs'],
    secondary: ['obliques'],
    stabiliser: ['front_delts', 'glutes'],
    instructions: [
      'Rest on your forearms and toes with elbows under your shoulders.',
      'Make a straight line from head to heels; squeeze your glutes and brace your abs.',
      'Hold without letting your hips sag or rise.',
    ],
    mistakes: ['Hips sagging towards the floor.', 'Holding your breath.'],
  },
  {
    name: 'Side plank',
    aliases: ['side bridge'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    unilateral: true,
    met: 3.8,
    primary: ['obliques'],
    secondary: ['abs'],
    stabiliser: ['abductors'],
    instructions: [
      'Lie on your side, propped on one forearm with your elbow under your shoulder.',
      'Lift your hips until your body is straight from head to feet.',
      'Hold, then switch sides.',
    ],
  },
  {
    name: 'Copenhagen plank',
    aliases: ['copenhagen adductor plank', 'copenhagen'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    unilateral: true,
    met: 3.8,
    primary: ['adductors'],
    secondary: ['obliques'],
    instructions: [
      'Lie on your side with your top leg resting on a bench, inside of the knee or ankle on the pad.',
      'Lift your hips so your body is straight and your bottom leg hangs free.',
      'Hold, then switch sides.',
    ],
    tips: ['Support at the knee is easier; at the ankle is harder.'],
  },
  {
    name: 'Crunch',
    aliases: ['crunches', 'ab crunch'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['abs'],
    instructions: [
      'Lie on your back with knees bent and hands lightly at your temples.',
      'Curl your shoulders off the floor by squeezing your abs.',
      'Lower slowly.',
    ],
    mistakes: ['Pulling on your neck.'],
  },
  {
    name: 'Sit-up',
    aliases: ['situp', 'sit ups'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['abs'],
    light: ['obliques'],
    instructions: [
      'Lie on your back with knees bent and feet anchored.',
      'Curl all the way up until your chest is near your thighs.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Decline sit-up',
    aliases: ['decline crunch'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'weighted_bodyweight',
    met: 3.8,
    primary: ['abs'],
    light: ['obliques'],
    instructions: [
      'Hook your feet under the pads of a decline bench and lie back.',
      'Curl up until your torso is upright.',
      'Lower slowly.',
    ],
    tips: ['Hold a plate on your chest to add weight.'],
  },
  {
    name: 'Cable crunch',
    aliases: ['kneeling cable crunch', 'rope crunch'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['abs'],
    instructions: [
      'Kneel facing a high pulley, holding a rope beside your head.',
      'Crunch down by curling your spine, bringing your elbows towards your knees.',
      'Return slowly.',
    ],
    mistakes: ['Sitting back on your heels and pulling with your arms.'],
  },
  {
    name: 'Machine crunch',
    aliases: ['ab machine', 'ab crunch machine'],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['abs'],
    instructions: [
      'Sit in the machine and hold the handles or pads.',
      'Crunch forward by curling your spine.',
      'Return slowly.',
    ],
  },
  {
    name: 'Reverse crunch',
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['abs'],
    instructions: [
      'Lie on your back with your knees bent up over your hips.',
      'Curl your hips off the floor, bringing your knees towards your chest.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Bicycle crunch',
    aliases: ['bicycle', 'cycle crunch'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['obliques', 'abs'],
    instructions: [
      'Lie on your back with hands at your temples and legs raised.',
      'Bring one elbow towards the opposite knee while straightening the other leg.',
      'Alternate sides in a pedalling motion.',
    ],
  },
  {
    name: 'Russian twist',
    aliases: ['seated twist'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'weighted_bodyweight',
    met: 3.8,
    primary: ['obliques'],
    secondary: ['abs'],
    instructions: [
      'Sit with knees bent and lean back slightly, feet on or off the floor.',
      'Rotate your torso to tap the floor beside one hip, then the other.',
      'Keep your chest up throughout.',
    ],
    tips: ['Hold a plate or dumbbell to add weight.'],
  },
  {
    name: 'Hanging leg raise',
    aliases: ['leg raise hanging', 'hanging straight leg raise'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['abs'],
    secondary: ['obliques'],
    light: ['forearms'],
    instructions: [
      'Hang from a pull-up bar with straight arms.',
      'Raise your straight legs until they’re at least parallel to the floor.',
      'Lower slowly without swinging.',
    ],
    mistakes: ['Swinging to get the legs up.'],
  },
  {
    name: 'Hanging knee raise',
    aliases: ['knee raise', 'hanging knee tuck'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['abs'],
    light: ['forearms'],
    instructions: [
      'Hang from a bar with straight arms.',
      'Pull your knees up towards your chest, curling your pelvis.',
      'Lower slowly.',
    ],
  },
  {
    name: "Captain's chair leg raise",
    aliases: ['roman chair leg raise', 'vertical knee raise', 'captains chair'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['abs'],
    instructions: [
      'Support yourself on the forearm pads with your back against the pad.',
      'Raise your knees or straight legs to hip height.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Lying leg raise',
    aliases: ['leg raise', 'floor leg raise'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['abs'],
    instructions: [
      'Lie on your back with legs straight and hands under your hips.',
      'Raise your legs to vertical while keeping your lower back on the floor.',
      'Lower slowly without touching the floor.',
    ],
  },
  {
    name: 'Toes-to-bar',
    aliases: ['t2b'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 4.5,
    primary: ['abs'],
    secondary: ['lats', 'obliques'],
    light: ['forearms'],
    instructions: [
      'Hang from a bar with straight arms.',
      'Press the bar down slightly and raise your feet until they touch the bar.',
      'Lower under control.',
    ],
  },
  {
    name: 'V-up',
    aliases: ['v ups', 'jackknife'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['abs'],
    instructions: [
      'Lie flat with arms overhead and legs straight.',
      'Lift your arms and legs together to meet over your hips.',
      'Lower back down slowly.',
    ],
  },
  {
    name: 'Flutter kicks',
    aliases: ['flutter kick', 'scissor kicks'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    met: 3.8,
    primary: ['abs'],
    instructions: [
      'Lie on your back with legs straight and a few inches off the floor.',
      'Kick your legs up and down in small, quick alternating movements.',
      'Keep your lower back pressed into the floor.',
    ],
  },
  {
    name: 'Ab wheel rollout',
    aliases: ['ab roller', 'ab wheel', 'rollout'],
    category: 'calisthenics',
    equipment: 'other',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 3.8,
    primary: ['abs'],
    secondary: ['lats'],
    light: ['obliques'],
    instructions: [
      'Kneel holding the ab wheel under your shoulders.',
      'Roll forward as far as you can while keeping your back flat.',
      'Pull yourself back using your abs.',
    ],
    mistakes: ['Letting your lower back sag at the far end.'],
  },
  {
    name: 'Dead bug',
    aliases: ['deadbug'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 2.8,
    primary: ['abs'],
    instructions: [
      'Lie on your back with arms pointing up and knees bent at 90° over your hips.',
      'Lower one arm and the opposite leg towards the floor, keeping your lower back down.',
      'Return and switch sides.',
    ],
  },
  {
    name: 'Bird dog',
    aliases: ['birddog', 'quadruped arm leg raise'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    met: 2.8,
    primary: ['lower_back'],
    secondary: ['glutes', 'abs'],
    instructions: [
      'Start on hands and knees.',
      'Reach one arm forward and the opposite leg back until both are level with your body.',
      'Hold briefly, return and switch sides.',
    ],
  },
  {
    name: 'Hollow body hold',
    aliases: ['hollow hold', 'hollow body'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'duration',
    met: 3.8,
    primary: ['abs'],
    instructions: [
      'Lie on your back, press your lower back into the floor and lift your shoulders and legs.',
      'Reach your arms overhead and keep your legs straight and low.',
      'Hold the banana shape without your lower back lifting.',
    ],
    tips: ['Bend your knees or bring your arms to your sides to make it easier.'],
  },
  {
    name: 'Pallof press',
    aliases: ['anti rotation press', 'paloff press'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['obliques'],
    secondary: ['abs'],
    instructions: [
      'Stand side-on to a pulley at chest height, holding the handle at your chest.',
      'Press it straight out in front, resisting the pull to rotate.',
      'Bring it back to your chest. Switch sides after the set.',
    ],
  },
  {
    name: 'Cable woodchopper',
    aliases: ['woodchop', 'wood chopper', 'cable chop'],
    equipment: 'cable',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['obliques'],
    secondary: ['abs'],
    light: ['front_delts'],
    instructions: [
      'Set a pulley high and stand side-on, holding the handle with both hands.',
      'Pull it diagonally down and across your body, rotating through your torso.',
      'Return slowly. Switch sides after the set.',
    ],
  },
  {
    name: 'Mountain climber',
    aliases: ['mountain climbers'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 8,
    primary: ['abs'],
    secondary: ['quads'],
    stabiliser: ['front_delts'],
    instructions: [
      'Start in a high plank position.',
      'Drive one knee towards your chest, then switch legs quickly.',
      'Keep your hips level and keep going for the set time.',
    ],
  },
  {
    name: 'Dragon flag',
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 4.5,
    primary: ['abs'],
    secondary: ['obliques'],
    light: ['lats'],
    instructions: [
      'Lie on a bench and grip it behind your head.',
      'Lift your whole body up onto your upper back, keeping it straight from shoulders to toes.',
      'Lower slowly as one straight line without bending at the hips.',
    ],
    tips: ['Start with negatives or tucked legs.'],
  },
]);
