import { defineExercises } from '../define.ts';

/** Olympic lifts, kettlebell work, carries and conditioning. */
export const fullBody = defineExercises([
  {
    name: 'Power clean',
    aliases: ['clean', 'barbell clean'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'powerClean',
    met: 6,
    primary: ['glutes', 'quads', 'traps'],
    secondary: ['hamstrings', 'lower_back', 'upper_back'],
    light: ['calves', 'forearms'],
    instructions: [
      'Start as for a deadlift, gripping the bar just outside your legs.',
      'Lift the bar to mid-thigh, then explode up by extending your hips, knees and ankles.',
      'Pull yourself under the bar and catch it on your front shoulders in a quarter squat.',
      'Stand up, then lower the bar back to the floor.',
    ],
    tips: ['Learn it from a coach; technique matters more than load.'],
    mistakes: ['Pulling early with the arms.', 'Catching with elbows pointing down.'],
  },
  {
    name: 'Hang clean',
    aliases: ['hang power clean'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 6,
    primary: ['glutes', 'quads', 'traps'],
    secondary: ['hamstrings', 'upper_back'],
    instructions: [
      'Stand holding the bar at your hips, then hinge until it’s just above your knees.',
      'Explode up and pull yourself under the bar.',
      'Catch it on your front shoulders and stand up.',
    ],
  },
  {
    name: 'Clean and jerk',
    aliases: ['c&j', 'clean & jerk'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 6,
    primary: ['quads', 'glutes', 'front_delts'],
    secondary: ['hamstrings', 'traps', 'triceps'],
    stabiliser: ['abs'],
    instructions: [
      'Clean the bar from the floor to your front shoulders.',
      'Dip and drive, then split your feet and punch the bar overhead.',
      'Recover your feet together with the bar locked out, then lower it.',
    ],
  },
  {
    name: 'Power snatch',
    aliases: ['snatch', 'barbell snatch'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 6,
    primary: ['glutes', 'quads', 'traps'],
    secondary: ['hamstrings', 'front_delts', 'upper_back'],
    stabiliser: ['abs'],
    instructions: [
      'Take a wide grip and set up as for a deadlift.',
      'Pull the bar past your knees, then explode up.',
      'Pull yourself under and catch the bar overhead with straight arms in a quarter squat.',
      'Stand up and lower the bar.',
    ],
  },
  {
    name: 'Barbell thruster',
    aliases: ['thruster', 'thrusters'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 8,
    primary: ['quads', 'front_delts'],
    secondary: ['glutes', 'triceps'],
    stabiliser: ['abs'],
    instructions: [
      'Hold the bar on your front shoulders.',
      'Front squat down, then drive up and use that momentum to press the bar overhead.',
      'Bring it back to your shoulders as you go into the next squat.',
    ],
  },
  {
    name: 'Dumbbell thruster',
    aliases: ['db thruster'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 8,
    primary: ['quads', 'front_delts'],
    secondary: ['glutes', 'triceps'],
    instructions: [
      'Hold dumbbells at your shoulders.',
      'Squat down, then drive up and press the dumbbells overhead.',
      'Lower to your shoulders as you squat again.',
    ],
  },
  {
    name: 'Kettlebell swing',
    aliases: ['kb swing', 'russian swing', 'two hand swing'],
    equipment: 'kettlebell',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 8,
    primary: ['glutes', 'hamstrings'],
    secondary: ['lower_back'],
    light: ['front_delts', 'forearms'],
    stabiliser: ['abs'],
    instructions: [
      'Stand with feet a little wider than your hips, kettlebell on the floor in front.',
      'Hike it back between your legs, then snap your hips forward to swing it to chest height.',
      'Let it fall back between your legs and hinge into the next rep.',
    ],
    tips: ['It’s a hip hinge, not a squat or a front raise.'],
    mistakes: ['Lifting the bell with your arms.', 'Squatting instead of hinging.'],
  },
  {
    name: 'Turkish get-up',
    aliases: ['tgu', 'get up', 'kettlebell get-up'],
    equipment: 'kettlebell',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    met: 5,
    primary: ['front_delts', 'abs'],
    secondary: ['glutes', 'obliques', 'quads'],
    stabiliser: ['triceps'],
    instructions: [
      'Lie on your back holding a kettlebell straight up in one hand, same-side knee bent.',
      'Roll onto your opposite elbow, then hand, and lift your hips.',
      'Sweep your leg under into a kneel, then stand up with the bell locked out overhead.',
      'Reverse the steps to lie back down. Switch sides after the set.',
    ],
    tips: ['Keep your eyes on the kettlebell the whole time.'],
  },
  {
    name: "Farmer's carry",
    aliases: ['farmers walk', 'farmer walk', 'loaded carry'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'distance_duration',
    met: 6,
    primary: ['forearms', 'traps'],
    secondary: ['abs', 'obliques'],
    light: ['quads', 'glutes'],
    instructions: [
      'Pick up heavy dumbbells or kettlebells and stand tall.',
      'Walk with short, quick steps, shoulders back and core braced.',
      'Go for distance or time, then set them down with control.',
    ],
  },
  {
    name: 'Suitcase carry',
    aliases: ['one arm carry', 'single arm farmers walk'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'distance_duration',
    unilateral: true,
    met: 5,
    primary: ['obliques', 'forearms'],
    secondary: ['traps', 'abs'],
    instructions: [
      'Hold a heavy dumbbell or kettlebell in one hand.',
      'Walk tall without leaning towards the weight.',
      'Switch hands and repeat.',
    ],
  },
  {
    name: 'Sled push',
    aliases: ['prowler push', 'sled'],
    category: 'cardio',
    equipment: 'other',
    mechanic: 'compound',
    logType: 'distance_duration',
    met: 8,
    primary: ['quads', 'glutes'],
    secondary: ['calves'],
    stabiliser: ['triceps', 'front_delts'],
    instructions: [
      'Grip the sled poles with arms extended and lean in at about 45°.',
      'Drive the sled forward with short, powerful steps.',
      'Push for the set distance.',
    ],
  },
  {
    name: 'Burpee',
    aliases: ['burpees'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 8,
    primary: ['quads', 'mid_lower_chest'],
    secondary: ['glutes', 'triceps', 'abs'],
    instructions: [
      'From standing, squat down and place your hands on the floor.',
      'Jump your feet back to a plank and do a push-up.',
      'Jump your feet back in and leap up with your arms overhead.',
    ],
  },
  {
    name: 'Battle ropes',
    aliases: ['battle rope', 'rope waves'],
    category: 'cardio',
    equipment: 'other',
    mechanic: 'compound',
    logType: 'duration',
    met: 8,
    primary: ['front_delts'],
    secondary: ['forearms', 'abs'],
    instructions: [
      'Hold a rope end in each hand and stand in a half squat.',
      'Whip the ropes up and down quickly to make waves.',
      'Keep going for the set time.',
    ],
  },
  {
    name: 'Medicine ball slam',
    aliases: ['ball slam', 'slam ball'],
    category: 'strength',
    equipment: 'other',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 7,
    primary: ['lats', 'abs'],
    secondary: ['front_delts', 'triceps'],
    instructions: [
      'Lift a slam ball overhead, rising onto your toes.',
      'Slam it into the floor as hard as you can, hinging at the hips.',
      'Pick it up and repeat.',
    ],
  },
  {
    name: 'Wall ball',
    aliases: ['wall balls', 'wall ball shot'],
    category: 'strength',
    equipment: 'other',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 8,
    primary: ['quads', 'front_delts'],
    secondary: ['glutes', 'triceps'],
    instructions: [
      'Hold a medicine ball at your chest facing a wall.',
      'Squat down, then drive up and throw the ball to a target on the wall.',
      'Catch it and go straight into the next squat.',
    ],
  },
  {
    name: 'Box jump',
    aliases: ['box jumps', 'plyo box jump'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    met: 8,
    primary: ['quads', 'glutes'],
    secondary: ['calves', 'hamstrings'],
    instructions: [
      'Stand facing a sturdy box.',
      'Swing your arms and jump onto the box, landing softly with bent knees.',
      'Stand up, then step back down.',
    ],
    mistakes: ['Jumping down, which is hard on the joints.'],
  },
]);
