import { defineExercises } from '../define.ts';

export const legs = defineExercises([
  // ─── Squats ───
  {
    name: 'Barbell back squat',
    aliases: ['squat', 'back squat', 'bb squat', 'high bar squat', 'low bar squat'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'backSquat',
    met: 6,
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    light: ['lower_back', 'hamstrings'],
    stabiliser: ['abs'],
    instructions: [
      'Set the bar on your upper back (not your neck) and step back from the rack.',
      'Stand with feet about shoulder width, toes turned out slightly.',
      'Brace and sit down between your hips until your thighs are at least parallel to the floor.',
      'Drive back up, keeping your chest up and knees tracking over your toes.',
    ],
    tips: [
      'Take a big breath and brace before each rep.',
      'Set the safety pins just below your bottom position.',
    ],
    mistakes: ['Knees caving in.', 'Heels lifting off the floor.', 'Cutting depth short.'],
  },
  {
    name: 'Barbell front squat',
    aliases: ['front squat', 'fs'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'frontSquat',
    met: 6,
    primary: ['quads'],
    secondary: ['glutes', 'upper_back'],
    light: ['adductors'],
    stabiliser: ['abs'],
    instructions: [
      'Rest the bar on your front shoulders, elbows high, in a clean grip or with arms crossed.',
      'Squat straight down, keeping your torso upright and elbows up.',
      'Drive back up to standing.',
    ],
    mistakes: ['Elbows dropping so the bar rolls forward.'],
  },
  {
    name: 'Box squat',
    aliases: ['barbell box squat'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    met: 6,
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'adductors'],
    light: ['lower_back'],
    instructions: [
      'Set a box behind you at about parallel depth.',
      'Squat back until you sit lightly on the box, staying tight.',
      'Drive up from the box without rocking.',
    ],
    mistakes: ['Relaxing completely on the box.'],
  },
  {
    name: 'Goblet squat',
    aliases: ['dumbbell goblet squat', 'kettlebell goblet squat', 'db squat'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    stabiliser: ['abs', 'upper_back'],
    instructions: [
      'Hold a dumbbell or kettlebell vertically against your chest.',
      'Squat down between your knees, keeping your chest up.',
      'Stand back up.',
    ],
    tips: ['A great way to learn the squat.'],
  },
  {
    name: 'Smith machine squat',
    aliases: ['smith squat'],
    equipment: 'smith',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    instructions: [
      'Set the bar on your upper back with your feet slightly in front of you.',
      'Unhook and squat down to at least parallel.',
      'Drive back up and re-hook at the end.',
    ],
  },
  {
    name: 'Hack squat',
    aliases: ['machine hack squat', 'hack squat machine'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['quads'],
    secondary: ['glutes'],
    light: ['adductors'],
    instructions: [
      'Stand on the platform with your back against the pad and shoulders under the pads.',
      'Release the safety and squat down as deep as you can control.',
      'Push back up without locking your knees hard.',
    ],
    tips: ['Feet lower on the platform for more quads, higher for more glutes.'],
  },
  {
    name: 'Pendulum squat',
    aliases: ['pendulum squat machine'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['quads'],
    secondary: ['glutes'],
    instructions: [
      'Step into the machine with your back on the pad and shoulders under the pads.',
      'Squat down as deep as you can while the platform swings in an arc.',
      'Drive back up.',
    ],
  },
  {
    name: 'Belt squat',
    aliases: ['belt squat machine'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    instructions: [
      'Attach the belt around your hips and stand on the platform.',
      'Squat down with your torso upright.',
      'Drive back up.',
    ],
    tips: ['Loads the legs without any weight on your spine.'],
  },
  {
    name: 'Leg press',
    aliases: ['45 degree leg press', 'leg press machine', 'sled press'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    light: ['hamstrings'],
    instructions: [
      'Sit in the machine with your feet shoulder width on the platform.',
      'Release the safeties and lower the platform until your knees are around 90° or deeper.',
      'Press back up without locking your knees.',
    ],
    tips: ['Log the plates you add, not the sled’s own weight.'],
    mistakes: [
      'Letting your lower back round off the pad at the bottom.',
      'Locking out the knees hard.',
    ],
  },
  {
    name: 'Single-leg leg press',
    aliases: ['one leg press'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['quads', 'glutes'],
    instructions: [
      'Place one foot in the middle of the platform.',
      'Lower until your knee is around 90°, then press up.',
      'Switch legs after the set.',
    ],
  },
  {
    name: 'Sissy squat',
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    primary: ['quads'],
    instructions: [
      'Stand holding a support, then rise onto your toes.',
      'Lean back and bend your knees forward, lowering your body in a straight line from knees to head.',
      'Push back up through your quads.',
    ],
  },
  // ─── Lunges and single leg ───
  {
    name: 'Dumbbell Bulgarian split squat',
    aliases: ['bulgarian split squat', 'bss', 'rear foot elevated split squat', 'rfess'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'bulgarianSplitSquat',
    unilateral: true,
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    light: ['hamstrings'],
    instructions: [
      'Stand a stride in front of a bench and rest the top of your back foot on it.',
      'Holding a dumbbell in each hand, lower until your back knee nearly touches the floor.',
      'Drive up through your front foot. Switch legs after the set.',
    ],
    tips: ['Log the weight of one dumbbell.', 'Lean forward a little for more glutes.'],
    mistakes: ['Front foot too close to the bench.'],
  },
  {
    name: 'Smith machine split squat',
    aliases: ['smith split squat', 'smith lunge'],
    equipment: 'smith',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['quads', 'glutes'],
    instructions: [
      'Set the bar on your upper back and take a long split stance.',
      'Lower straight down until your back knee nearly touches the floor.',
      'Drive back up. Switch legs after the set.',
    ],
  },
  {
    name: 'Dumbbell walking lunge',
    aliases: ['walking lunge', 'lunges', 'db lunge'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    light: ['hamstrings'],
    instructions: [
      'Hold dumbbells at your sides and step forward into a lunge.',
      'Lower until your back knee nearly touches the floor.',
      'Push through your front foot and step straight into the next lunge.',
    ],
  },
  {
    name: 'Dumbbell reverse lunge',
    aliases: ['reverse lunge', 'back lunge'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    instructions: [
      'Stand holding dumbbells at your sides.',
      'Step back and lower until your back knee nearly touches the floor.',
      'Push through your front foot to return to standing.',
    ],
    tips: ['Kinder to the knees than forward lunges.'],
  },
  {
    name: 'Barbell reverse lunge',
    aliases: ['barbell lunge'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['quads', 'glutes'],
    secondary: ['adductors'],
    stabiliser: ['abs'],
    instructions: [
      'Set a barbell on your upper back.',
      'Step back into a lunge until your back knee nearly touches the floor.',
      'Drive back to standing and alternate legs.',
    ],
  },
  {
    name: 'Dumbbell step-up',
    aliases: ['step up', 'box step-up'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['quads', 'glutes'],
    instructions: [
      'Stand facing a box or bench holding dumbbells.',
      'Place one foot on the box and drive up through it to stand on top.',
      'Step down under control. Switch legs after the set.',
    ],
    mistakes: ['Pushing off the back foot.'],
  },
  {
    name: 'Lateral lunge',
    aliases: ['side lunge', 'cossack lunge'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['adductors', 'glutes'],
    secondary: ['quads'],
    instructions: [
      'Stand with feet together holding a dumbbell at your chest.',
      'Take a wide step to the side and sit back into that hip, keeping the other leg straight.',
      'Push back to the start.',
    ],
  },
  // ─── Hinges and glutes ───
  {
    name: 'Barbell Romanian deadlift',
    aliases: ['rdl', 'romanian deadlift', 'barbell rdl', 'bb rdl'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'romanianDeadlift',
    met: 6,
    primary: ['hamstrings', 'glutes'],
    secondary: ['lower_back'],
    light: ['forearms'],
    instructions: [
      'Stand holding a barbell at your hips, feet hip width apart.',
      'With soft knees, push your hips back and lower the bar down your thighs.',
      'Stop when you feel a strong hamstring stretch, usually just below the knees.',
      'Drive your hips forward to stand tall.',
    ],
    tips: ['Keep the bar touching your legs the whole way.'],
    mistakes: ['Rounding the back to reach lower.', 'Bending the knees so it becomes a deadlift.'],
  },
  {
    name: 'Dumbbell Romanian deadlift',
    aliases: ['db rdl', 'dumbbell rdl'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['hamstrings', 'glutes'],
    secondary: ['lower_back'],
    instructions: [
      'Hold dumbbells in front of your thighs.',
      'Hinge at the hips with soft knees, sliding the dumbbells down your legs.',
      'Drive your hips forward to stand.',
    ],
  },
  {
    name: 'Single-leg Romanian deadlift',
    aliases: ['single leg rdl', 'sl rdl', 'one leg rdl'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['hamstrings', 'glutes'],
    stabiliser: ['abductors', 'lower_back'],
    instructions: [
      'Stand on one leg holding a dumbbell in the opposite hand.',
      'Hinge forward, letting the free leg rise behind you, until your torso is near parallel.',
      'Return to standing. Switch legs after the set.',
    ],
  },
  {
    name: 'Stiff-leg deadlift',
    aliases: ['sldl', 'stiff legged deadlift'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['hamstrings'],
    secondary: ['glutes', 'lower_back'],
    instructions: [
      'Stand with the bar on the floor and legs almost straight.',
      'Hinge down with a flat back and grip the bar.',
      'Stand up by driving your hips forward, then lower with control.',
    ],
  },
  {
    name: 'Good morning',
    aliases: ['barbell good morning'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['hamstrings', 'lower_back'],
    secondary: ['glutes'],
    instructions: [
      'Set a barbell on your upper back as for a squat.',
      'With soft knees, hinge forward until your torso is near parallel.',
      'Drive your hips forward to stand.',
    ],
    tips: ['Start light; this loads the lower back a lot.'],
  },
  {
    name: 'Barbell hip thrust',
    aliases: ['hip thrust', 'glute thrust', 'bb hip thrust'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'hipThrust',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    light: ['quads', 'adductors'],
    instructions: [
      'Sit with your upper back against a bench and a padded barbell over your hips.',
      'Plant your feet so your shins are vertical at the top.',
      'Drive through your heels to lift your hips until your body is flat from knees to shoulders.',
      'Lower under control.',
    ],
    tips: ['Tuck your chin and keep your ribs down at the top.'],
    mistakes: ['Over-arching the lower back instead of squeezing the glutes.'],
  },
  {
    name: 'Smith machine hip thrust',
    aliases: ['smith hip thrust'],
    equipment: 'smith',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    instructions: [
      'Set a bench beside the Smith machine with the bar over your hips.',
      'Drive your hips up to lockout, squeezing your glutes.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Machine hip thrust',
    aliases: ['glute drive', 'hip thrust machine'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    instructions: [
      'Sit in the machine with the belt or pad across your hips.',
      'Drive your hips up until they’re fully extended.',
      'Lower under control.',
    ],
  },
  {
    name: 'Glute bridge',
    aliases: ['bridge', 'floor bridge', 'hip bridge'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    primary: ['glutes'],
    light: ['hamstrings'],
    instructions: [
      'Lie on your back with knees bent and feet flat.',
      'Squeeze your glutes and lift your hips until your body is straight from knees to shoulders.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Cable pull-through',
    aliases: ['pull through', 'rope pull through'],
    equipment: 'cable',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['glutes', 'hamstrings'],
    instructions: [
      'Face away from a low pulley holding a rope between your legs.',
      'Hinge back, letting the rope pull your hands through your legs.',
      'Drive your hips forward to stand tall.',
    ],
  },
  {
    name: 'Cable glute kickback',
    aliases: ['glute kickback', 'cable kickback', 'donkey kickback cable'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['glutes'],
    instructions: [
      'Strap an ankle cuff to a low pulley and face the machine.',
      'Kick your leg straight back, squeezing your glute.',
      'Return slowly. Switch legs after the set.',
    ],
    mistakes: ['Arching your lower back to kick higher.'],
  },
  // ─── Knee flexion and extension ───
  {
    name: 'Leg extension',
    aliases: ['quad extension', 'leg extension machine'],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['quads'],
    instructions: [
      'Sit with the pad on your lower shins and knees lined up with the machine’s pivot.',
      'Straighten your legs fully.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Lying leg curl',
    aliases: ['leg curl', 'prone leg curl', 'hamstring curl'],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['hamstrings'],
    light: ['calves'],
    instructions: [
      'Lie face down with the pad just above your heels.',
      'Curl your heels towards your glutes.',
      'Lower slowly to straight legs.',
    ],
    mistakes: ['Lifting your hips off the pad.'],
  },
  {
    name: 'Seated leg curl',
    aliases: ['seated hamstring curl'],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['hamstrings'],
    instructions: [
      'Sit with the pad behind your lower calves and the thigh pad locked down.',
      'Curl your heels down and back.',
      'Return slowly.',
    ],
  },
  {
    name: 'Glute-ham raise',
    aliases: ['ghr'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    primary: ['hamstrings'],
    secondary: ['glutes'],
    instructions: [
      'Set your feet in the glute-ham developer with knees just behind the pad.',
      'Lower your torso forward under control.',
      'Curl yourself back up with your hamstrings.',
    ],
  },
  // ─── Hips ───
  {
    name: 'Hip abduction machine',
    aliases: ['abductor machine', 'outer thigh machine', 'hip abduction'],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['abductors'],
    secondary: ['glutes'],
    instructions: [
      'Sit with the pads against the outside of your knees.',
      'Push your knees apart as far as you can.',
      'Return slowly.',
    ],
    tips: ['Lean forward slightly to work more of the glutes.'],
  },
  {
    name: 'Hip adduction machine',
    aliases: ['adductor machine', 'inner thigh machine', 'hip adduction'],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['adductors'],
    instructions: [
      'Sit with the pads against the inside of your knees.',
      'Squeeze your knees together.',
      'Return slowly to a stretch.',
    ],
  },
  {
    name: 'Cable hip abduction',
    aliases: ['standing cable abduction'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['abductors'],
    secondary: ['glutes'],
    instructions: [
      'Attach an ankle cuff to a low pulley and stand side-on.',
      'Lift your outside leg out to the side.',
      'Return slowly. Switch legs after the set.',
    ],
  },
  {
    name: 'Band lateral walk',
    aliases: ['monster walk', 'band walk', 'lateral band walk'],
    equipment: 'band',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    primary: ['abductors', 'glutes'],
    instructions: [
      'Place a mini band around your knees or ankles and sit into a half squat.',
      'Step sideways, keeping tension on the band.',
      'Take the same number of steps back the other way.',
    ],
  },
  // ─── Calves ───
  {
    name: 'Standing calf raise',
    aliases: ['calf raise', 'standing calf raise machine'],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['calves'],
    instructions: [
      'Stand with your shoulders under the pads and the balls of your feet on the step.',
      'Lower your heels for a full stretch.',
      'Rise as high as you can onto your toes.',
    ],
    tips: ['Pause at the bottom to stop the bounce.'],
    mistakes: ['Short, bouncy reps.'],
  },
  {
    name: 'Seated calf raise',
    aliases: ['seated calf'],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['calves'],
    instructions: [
      'Sit with the pad across your lower thighs and the balls of your feet on the platform.',
      'Lower your heels for a stretch.',
      'Push up onto your toes.',
    ],
  },
  {
    name: 'Leg press calf raise',
    aliases: ['calf press', 'leg press calf'],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['calves'],
    instructions: [
      'Sit in the leg press with the balls of your feet on the bottom edge of the platform.',
      'Push the platform with your toes, extending your ankles fully.',
      'Let your toes come back towards you for a stretch.',
    ],
    tips: ['Keep the safeties engaged.'],
  },
  {
    name: 'Smith machine calf raise',
    aliases: ['smith calf raise'],
    equipment: 'smith',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['calves'],
    instructions: [
      'Stand on a step under the Smith bar with the balls of your feet on the edge.',
      'Lower your heels, then rise high onto your toes.',
      'Repeat with a pause at the bottom.',
    ],
  },
  {
    name: 'Single-leg dumbbell calf raise',
    aliases: ['single leg calf raise', 'one leg calf raise'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['calves'],
    instructions: [
      'Stand on one foot on a step, holding a dumbbell and a support.',
      'Lower your heel, then rise as high as you can.',
      'Switch legs after the set.',
    ],
  },
]);
