import { defineExercises } from '../define.ts';

export const shoulders = defineExercises([
  {
    name: 'Barbell overhead press',
    aliases: [
      'ohp',
      'overhead press',
      'military press',
      'standing press',
      'shoulder press barbell',
    ],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'overheadPress',
    met: 6,
    primary: ['front_delts'],
    secondary: ['triceps', 'side_delts'],
    light: ['upper_chest', 'traps'],
    stabiliser: ['abs'],
    instructions: [
      'Stand with the bar on your front shoulders, hands just outside shoulder width.',
      'Brace your core and squeeze your glutes.',
      'Press the bar straight up, moving your head back and then through once it passes your face.',
      'Lock out overhead with the bar over your mid-foot, then lower to your shoulders.',
    ],
    tips: ['Squeeze your glutes to stop your lower back arching.'],
    mistakes: [
      'Leaning back into a standing incline press.',
      'Pressing the bar forward around your face.',
    ],
  },
  {
    name: 'Push press',
    aliases: ['barbell push press'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'pushPress',
    met: 6,
    primary: ['front_delts'],
    secondary: ['triceps', 'quads'],
    light: ['side_delts', 'traps', 'glutes'],
    instructions: [
      'Start with the bar on your front shoulders as for an overhead press.',
      'Dip a few inches by bending your knees, keeping your torso upright.',
      'Drive up hard through your legs and use that momentum to press the bar overhead.',
      'Lower it back to your shoulders under control.',
    ],
    mistakes: [
      'Dipping by bending forward at the hips.',
      'Pressing before the legs finish driving.',
    ],
  },
  {
    name: 'Dumbbell shoulder press',
    aliases: [
      'db shoulder press',
      'seated dumbbell press',
      'dumbbell overhead press',
      'shoulder press',
    ],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    rankKey: 'dumbbellShoulderPress',
    primary: ['front_delts'],
    secondary: ['triceps', 'side_delts'],
    light: ['upper_chest'],
    instructions: [
      'Sit on an upright bench with a dumbbell in each hand at shoulder height.',
      'Press the dumbbells overhead until your arms are straight.',
      'Lower them back to shoulder level under control.',
    ],
    tips: ['Log the weight of one dumbbell.', 'Keep your forearms vertical at the bottom.'],
    mistakes: ['Arching your lower back off the pad.', 'Cutting the range short at the bottom.'],
  },
  {
    name: 'Arnold press',
    aliases: ['arnold dumbbell press'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['front_delts'],
    secondary: ['side_delts', 'triceps'],
    instructions: [
      'Sit holding dumbbells in front of your shoulders, palms facing you.',
      'Press up while rotating your palms to face forward at the top.',
      'Reverse the rotation as you lower.',
    ],
  },
  {
    name: 'Machine shoulder press',
    aliases: ['shoulder press machine', 'seated shoulder press'],
    equipment: 'machine',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['front_delts'],
    secondary: ['triceps', 'side_delts'],
    instructions: [
      'Adjust the seat so the handles start at shoulder height.',
      'Press the handles up until your arms are straight.',
      'Lower slowly and repeat.',
    ],
  },
  {
    name: 'Smith machine shoulder press',
    aliases: ['smith shoulder press', 'smith overhead press'],
    equipment: 'smith',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['front_delts'],
    secondary: ['triceps', 'side_delts'],
    instructions: [
      'Set an upright bench under the Smith bar so it travels just in front of your face.',
      'Unhook and lower the bar to chin height.',
      'Press back up to lockout.',
    ],
  },
  {
    name: 'Landmine press',
    aliases: ['single arm landmine press', 'half kneeling landmine press'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['front_delts', 'upper_chest'],
    secondary: ['triceps'],
    stabiliser: ['obliques'],
    instructions: [
      'Wedge one end of a barbell into a corner or landmine and hold the other end at shoulder height.',
      'Press the bar up and forward until your arm is straight.',
      'Lower back to your shoulder and switch sides after the set.',
    ],
    tips: ['Shoulder-friendly when straight overhead pressing hurts.'],
  },
  {
    name: 'Dumbbell lateral raise',
    aliases: ['lateral raise', 'side raise', 'side lateral', 'lat raise', 'db lateral raise'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['side_delts'],
    light: ['traps', 'front_delts'],
    instructions: [
      'Stand holding light dumbbells at your sides.',
      'With a slight bend in your elbows, raise them out to the sides until they reach shoulder height.',
      'Lower slowly.',
    ],
    tips: ['Lead with your elbows and think about pushing the dumbbells out, not up.'],
    mistakes: ['Swinging the weight with your body.', 'Shrugging your shoulders up to your ears.'],
  },
  {
    name: 'Cable lateral raise',
    aliases: ['single arm cable lateral', 'cable side raise'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['side_delts'],
    light: ['traps'],
    instructions: [
      'Set a pulley low and stand side-on, holding the handle with the far hand.',
      'Raise your arm out to the side to shoulder height.',
      'Lower slowly and switch sides after the set.',
    ],
  },
  {
    name: 'Machine lateral raise',
    aliases: ['lateral raise machine', 'side raise machine'],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['side_delts'],
    instructions: [
      'Sit with the pads against the outside of your upper arms.',
      'Raise your arms out to the sides until they’re level with your shoulders.',
      'Lower under control.',
    ],
  },
  {
    name: 'Dumbbell front raise',
    aliases: ['front raise', 'db front raise'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['front_delts'],
    light: ['upper_chest'],
    instructions: [
      'Stand holding dumbbells in front of your thighs.',
      'Raise them straight in front of you to shoulder height.',
      'Lower slowly.',
    ],
    mistakes: ['Leaning back to swing the weight up.'],
  },
  {
    name: 'Plate front raise',
    aliases: ['plate raise'],
    equipment: 'other',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['front_delts'],
    light: ['upper_chest'],
    instructions: [
      'Hold a plate with both hands at the sides (three and nine o’clock).',
      'Raise it in front of you to eye level.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Barbell upright row',
    aliases: ['upright row'],
    equipment: 'barbell',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['side_delts', 'traps'],
    light: ['biceps', 'front_delts'],
    instructions: [
      'Stand holding a barbell in front of your thighs, hands about shoulder width.',
      'Pull the bar up along your body, leading with your elbows, to lower-chest height.',
      'Lower slowly.',
    ],
    tips: ['A wider grip is easier on the shoulders.'],
    mistakes: ['Pulling the bar up to your chin with a narrow grip.'],
  },
  {
    name: 'Dumbbell rear delt fly',
    aliases: ['reverse fly', 'bent over reverse fly', 'rear delt raise', 'bent over lateral raise'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['rear_delts'],
    secondary: ['upper_back'],
    instructions: [
      'Hinge forward until your torso is nearly parallel to the floor, dumbbells hanging under your chest.',
      'With a slight bend in your elbows, raise the dumbbells out to the sides.',
      'Lower under control.',
    ],
    mistakes: ['Squeezing the shoulder blades so hard the upper back takes over.'],
  },
  {
    name: 'Reverse pec deck',
    aliases: ['rear delt machine', 'reverse fly machine', 'rear delt fly', 'reverse butterfly'],
    equipment: 'machine',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['rear_delts'],
    secondary: ['upper_back'],
    instructions: [
      'Sit facing the pec deck pad with the handles set to the rear position.',
      'Grip the handles at shoulder height and sweep your arms back in a wide arc.',
      'Return slowly.',
    ],
  },
  {
    name: 'Cable face pull',
    aliases: ['face pull', 'rope face pull'],
    equipment: 'cable',
    mechanic: 'compound',
    logType: 'weight_reps',
    primary: ['rear_delts'],
    secondary: ['upper_back', 'traps'],
    instructions: [
      'Attach a rope to a pulley at face height and grip it with thumbs pointing back.',
      'Pull the rope towards your face, splitting the ends and driving your elbows high and back.',
      'Return slowly.',
    ],
    tips: ['Finish with your hands beside your ears, like a double-biceps pose.'],
    mistakes: ['Leaning back and rowing with your body.'],
  },
  {
    name: 'Cable rear delt fly',
    aliases: ['cable reverse fly', 'cross cable rear delt'],
    equipment: 'cable',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['rear_delts'],
    light: ['upper_back'],
    instructions: [
      'Set both pulleys at shoulder height and cross the cables, holding the left cable in your right hand and vice versa.',
      'With straight arms, pull the cables apart and back.',
      'Return under control.',
    ],
  },
  {
    name: 'Band pull-apart',
    aliases: ['pull apart'],
    equipment: 'band',
    mechanic: 'isolation',
    logType: 'bodyweight_reps',
    primary: ['rear_delts'],
    secondary: ['upper_back'],
    instructions: [
      'Hold a band in front of you at shoulder height, hands shoulder width apart.',
      'Pull the band apart until it touches your chest, keeping your arms straight.',
      'Return slowly.',
    ],
    tips: ['A great warm-up before pressing.'],
  },
  {
    name: 'Incline Y-raise',
    aliases: ['y raise', 'prone y raise'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    logType: 'weight_reps',
    primary: ['traps'],
    secondary: ['side_delts', 'rear_delts'],
    instructions: [
      'Lie chest-down on an incline bench holding light dumbbells.',
      'Raise your arms up and out into a Y shape, thumbs up.',
      'Lower slowly.',
    ],
    tips: ['Use very light weights; this targets the lower traps.'],
  },
  {
    name: 'Kettlebell overhead press',
    aliases: ['kb press', 'kettlebell press'],
    equipment: 'kettlebell',
    mechanic: 'compound',
    logType: 'weight_reps',
    unilateral: true,
    primary: ['front_delts'],
    secondary: ['triceps'],
    stabiliser: ['obliques'],
    instructions: [
      'Clean the kettlebell to the rack position at your shoulder.',
      'Press it overhead until your arm is straight.',
      'Lower back to the rack and switch sides after the set.',
    ],
  },
]);
