import { defineExercises } from '../define.ts';

/** Calisthenics skills and their progressions. Static holds log as duration. */
export const skills = defineExercises([
  // ─── Handstand ───
  {
    name: 'Wall handstand',
    aliases: ['handstand hold wall', 'chest to wall handstand'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 3.5,
    primary: ['front_delts'],
    secondary: ['traps', 'triceps'],
    stabiliser: ['abs'],
    instructions: [
      'Place your hands about a hand’s width from a wall and walk your feet up until you’re upside down.',
      'Push the floor away, squeeze your legs together and keep your body straight.',
      'Hold for time, then walk down.',
    ],
    tips: ['Chest facing the wall teaches a straighter line than back to the wall.'],
  },
  {
    name: 'Freestanding handstand',
    aliases: ['handstand', 'handstand hold'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    rankKey: 'handstand',
    met: 3.5,
    primary: ['front_delts'],
    secondary: ['traps', 'forearms'],
    stabiliser: ['abs', 'triceps'],
    instructions: [
      'Kick up to a handstand away from any wall.',
      'Balance using pressure through your fingers and palms.',
      'Hold as long as you can stay straight, then step down.',
    ],
  },
  {
    name: 'Handstand push-up',
    aliases: ['hspu', 'wall handstand push-up', 'handstand pushup'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'bodyweight_reps',
    rankKey: 'handstandPushUp',
    met: 6,
    primary: ['front_delts'],
    secondary: ['triceps', 'traps'],
    light: ['upper_chest'],
    stabiliser: ['abs'],
    instructions: [
      'Kick up to a handstand facing away from a wall, hands shoulder width apart.',
      'Lower until the top of your head lightly touches the floor (or a mat).',
      'Press back up to straight arms.',
    ],
    tips: ['Master elevated pike push-ups first.'],
    mistakes: ['Letting the elbows flare wide.', 'Crashing your head into the floor.'],
  },
  // ─── L-sit ───
  {
    name: 'Tuck L-sit',
    aliases: ['tuck sit', 'l-sit tuck'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 3.5,
    primary: ['abs'],
    secondary: ['triceps'],
    stabiliser: ['front_delts'],
    instructions: [
      'Support yourself on parallettes, dip bars or the floor with straight arms.',
      'Lift your feet and hold your knees tucked to your chest.',
      'Hold for time.',
    ],
  },
  {
    name: 'L-sit',
    aliases: ['lsit', 'l sit hold'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    rankKey: 'lSit',
    met: 3.5,
    primary: ['abs'],
    secondary: ['triceps', 'quads'],
    stabiliser: ['front_delts'],
    instructions: [
      'Support yourself on straight arms with your hands beside your hips.',
      'Lift your straight legs until they’re parallel to the floor.',
      'Push your shoulders down and hold for time.',
    ],
  },
  // ─── Front lever ───
  {
    name: 'Tuck front lever',
    aliases: ['front lever tuck', 'tuck fl'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 4,
    primary: ['lats'],
    secondary: ['abs', 'rear_delts'],
    instructions: [
      'Hang from a bar and pull your knees to your chest.',
      'With straight arms, lift your hips until your back is level with the floor.',
      'Hold for time.',
    ],
  },
  {
    name: 'Advanced tuck front lever',
    aliases: ['adv tuck front lever', 'advanced tuck fl'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 4,
    primary: ['lats'],
    secondary: ['abs', 'rear_delts'],
    instructions: [
      'From a tuck front lever, open your hips so your back is flat and knees sit under your hips.',
      'Keep your arms straight and your body level.',
      'Hold for time.',
    ],
  },
  {
    name: 'Straddle front lever',
    aliases: ['straddle fl'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 4,
    primary: ['lats'],
    secondary: ['abs', 'rear_delts'],
    light: ['lower_back'],
    instructions: [
      'Hang from a bar and lift your body horizontal with your legs straight and wide apart.',
      'Keep your arms straight and hips level.',
      'Hold for time.',
    ],
  },
  {
    name: 'Front lever',
    aliases: ['full front lever', 'fl'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    rankKey: 'frontLever',
    met: 4,
    primary: ['lats'],
    secondary: ['abs', 'rear_delts'],
    light: ['lower_back', 'upper_back'],
    instructions: [
      'Hang from a bar with an overhand grip.',
      'With straight arms, lift your whole body horizontal, legs together and face up.',
      'Hold the line from shoulders to feet for time.',
    ],
    tips: ['Count only holds where your hips stay level with your shoulders.'],
  },
  // ─── Back lever ───
  {
    name: 'Tuck back lever',
    aliases: ['back lever tuck'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 4,
    primary: ['lats', 'mid_lower_chest'],
    secondary: ['biceps'],
    stabiliser: ['front_delts'],
    instructions: [
      'On rings or a bar, rotate backwards through a skin-the-cat until your body faces down.',
      'Hold with knees tucked and your back level with the floor.',
      'Hold for time, then rotate back.',
    ],
  },
  {
    name: 'Back lever',
    aliases: ['full back lever', 'bl'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    rankKey: 'backLever',
    met: 4,
    primary: ['lats', 'mid_lower_chest'],
    secondary: ['biceps', 'lower_back'],
    stabiliser: ['front_delts'],
    instructions: [
      'From an inverted hang, lower your body backwards until it’s horizontal and facing down.',
      'Keep your arms straight, legs together and body in one line.',
      'Hold for time.',
    ],
    tips: ['Build up slowly: this puts a lot of stress on the biceps tendons.'],
  },
  // ─── Planche ───
  {
    name: 'Planche lean',
    aliases: ['planche leans'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 3.5,
    primary: ['front_delts'],
    secondary: ['mid_lower_chest'],
    stabiliser: ['abs', 'biceps'],
    instructions: [
      'Start in a push-up position with fingers turned out.',
      'Lean your shoulders forward past your hands, arms locked straight.',
      'Hold for time.',
    ],
  },
  {
    name: 'Tuck planche',
    aliases: ['planche tuck'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 4,
    primary: ['front_delts'],
    secondary: ['mid_lower_chest', 'triceps'],
    stabiliser: ['abs'],
    instructions: [
      'With hands on the floor or parallettes, lean forward and lift your feet, knees tucked to your chest.',
      'Keep your arms straight and your back rounded.',
      'Hold for time.',
    ],
  },
  {
    name: 'Advanced tuck planche',
    aliases: ['adv tuck planche'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 4,
    primary: ['front_delts'],
    secondary: ['mid_lower_chest', 'triceps'],
    stabiliser: ['abs'],
    instructions: [
      'From a tuck planche, flatten your back so your hips rise to shoulder height.',
      'Keep your knees tucked under your hips and arms straight.',
      'Hold for time.',
    ],
  },
  {
    name: 'Straddle planche',
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 4,
    primary: ['front_delts'],
    secondary: ['mid_lower_chest', 'triceps'],
    stabiliser: ['abs', 'glutes'],
    instructions: [
      'Lean forward over straight arms and lift your straight legs, spread wide, until your body is horizontal.',
      'Hold for time.',
    ],
  },
  {
    name: 'Full planche',
    aliases: ['planche', 'full planche hold'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    rankKey: 'planche',
    met: 4,
    primary: ['front_delts'],
    secondary: ['mid_lower_chest', 'triceps'],
    stabiliser: ['abs', 'glutes', 'lower_back'],
    instructions: [
      'Lean forward over straight arms and lift your body horizontal with legs together.',
      'Keep your whole body in one line just above the floor.',
      'Hold for time.',
    ],
  },
  // ─── Other ───
  {
    name: 'Human flag',
    aliases: ['flag'],
    category: 'calisthenics',
    equipment: 'bodyweight',
    mechanic: 'compound',
    logType: 'duration',
    met: 4,
    primary: ['obliques', 'lats'],
    secondary: ['side_delts'],
    stabiliser: ['abs'],
    instructions: [
      'Grip a vertical pole with your hands wide, top arm pulling and bottom arm pushing.',
      'Lift your body sideways until it’s horizontal.',
      'Hold for time.',
    ],
  },
]);
